// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.outputs;

import com.pulumi.core.annotations.CustomType;
import io.chronosphere.chronosphere.outputs.ConsumptionConfigPartitionPartitionPartitionFilterCondition;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ConsumptionConfigPartitionPartitionPartitionFilter {
    /**
     * @return Conditions evaluated by the filter. Each condition matches by dataset, logs, metrics, or trace data; exactly one of `log_filter`, `metric_filter`, or `dataset_id` must be set per condition.
     * 
     */
    private @Nullable List<ConsumptionConfigPartitionPartitionPartitionFilterCondition> conditions;
    /**
     * @return Match operator (e.g. `IN`, `NOT_IN`) applied to the filter conditions.
     * 
     */
    private @Nullable String operator;

    private ConsumptionConfigPartitionPartitionPartitionFilter() {}
    /**
     * @return Conditions evaluated by the filter. Each condition matches by dataset, logs, metrics, or trace data; exactly one of `log_filter`, `metric_filter`, or `dataset_id` must be set per condition.
     * 
     */
    public List<ConsumptionConfigPartitionPartitionPartitionFilterCondition> conditions() {
        return this.conditions == null ? List.of() : this.conditions;
    }
    /**
     * @return Match operator (e.g. `IN`, `NOT_IN`) applied to the filter conditions.
     * 
     */
    public Optional<String> operator() {
        return Optional.ofNullable(this.operator);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ConsumptionConfigPartitionPartitionPartitionFilter defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<ConsumptionConfigPartitionPartitionPartitionFilterCondition> conditions;
        private @Nullable String operator;
        public Builder() {}
        public Builder(ConsumptionConfigPartitionPartitionPartitionFilter defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.conditions = defaults.conditions;
    	      this.operator = defaults.operator;
        }

        @CustomType.Setter
        public Builder conditions(@Nullable List<ConsumptionConfigPartitionPartitionPartitionFilterCondition> conditions) {
            this.conditions = conditions;
            return this;
        }
        public Builder conditions(ConsumptionConfigPartitionPartitionPartitionFilterCondition... conditions) {
            return conditions(List.of(conditions));
        }
        @CustomType.Setter
        public Builder operator(@Nullable String operator) {
            this.operator = operator;
            return this;
        }
        public ConsumptionConfigPartitionPartitionPartitionFilter build() {
            final var o = new ConsumptionConfigPartitionPartitionPartitionFilter();
            o.conditions = conditions;
            o.operator = operator;
            return o;
        }
    }
}
