// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class DerivedLabelMetricLabelMappingLabelNameMappingFilter {
    /**
     * @return Name of the label to match.
     * 
     */
    private String name;
    /**
     * @return Glob pattern matched against the label value.
     * 
     */
    private String valueGlob;

    private DerivedLabelMetricLabelMappingLabelNameMappingFilter() {}
    /**
     * @return Name of the label to match.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Glob pattern matched against the label value.
     * 
     */
    public String valueGlob() {
        return this.valueGlob;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DerivedLabelMetricLabelMappingLabelNameMappingFilter defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        private String valueGlob;
        public Builder() {}
        public Builder(DerivedLabelMetricLabelMappingLabelNameMappingFilter defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.valueGlob = defaults.valueGlob;
        }

        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("DerivedLabelMetricLabelMappingLabelNameMappingFilter", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder valueGlob(String valueGlob) {
            if (valueGlob == null) {
              throw new MissingRequiredPropertyException("DerivedLabelMetricLabelMappingLabelNameMappingFilter", "valueGlob");
            }
            this.valueGlob = valueGlob;
            return this;
        }
        public DerivedLabelMetricLabelMappingLabelNameMappingFilter build() {
            final var _resultValue = new DerivedLabelMetricLabelMappingLabelNameMappingFilter();
            _resultValue.name = name;
            _resultValue.valueGlob = valueGlob;
            return _resultValue;
        }
    }
}
