// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.chronosphere.chronosphere.outputs.DerivedLabelMetricLabelMappingLabelNameMappingFilter;
import io.chronosphere.chronosphere.outputs.DerivedLabelMetricLabelMappingLabelNameMappingValueMapping;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class DerivedLabelMetricLabelMappingLabelNameMapping {
    /**
     * @return Label filters that must all match for this name mapping to apply.
     * 
     */
    private List<DerivedLabelMetricLabelMappingLabelNameMappingFilter> filters;
    /**
     * @return Source label on the ingested time series to copy into the derived label.
     * 
     */
    private String sourceLabel;
    /**
     * @return Translations from source label values to a normalized target value. Each entry maps a set of source globs to a single target.
     * 
     */
    private @Nullable List<DerivedLabelMetricLabelMappingLabelNameMappingValueMapping> valueMappings;

    private DerivedLabelMetricLabelMappingLabelNameMapping() {}
    /**
     * @return Label filters that must all match for this name mapping to apply.
     * 
     */
    public List<DerivedLabelMetricLabelMappingLabelNameMappingFilter> filters() {
        return this.filters;
    }
    /**
     * @return Source label on the ingested time series to copy into the derived label.
     * 
     */
    public String sourceLabel() {
        return this.sourceLabel;
    }
    /**
     * @return Translations from source label values to a normalized target value. Each entry maps a set of source globs to a single target.
     * 
     */
    public List<DerivedLabelMetricLabelMappingLabelNameMappingValueMapping> valueMappings() {
        return this.valueMappings == null ? List.of() : this.valueMappings;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DerivedLabelMetricLabelMappingLabelNameMapping defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<DerivedLabelMetricLabelMappingLabelNameMappingFilter> filters;
        private String sourceLabel;
        private @Nullable List<DerivedLabelMetricLabelMappingLabelNameMappingValueMapping> valueMappings;
        public Builder() {}
        public Builder(DerivedLabelMetricLabelMappingLabelNameMapping defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.filters = defaults.filters;
    	      this.sourceLabel = defaults.sourceLabel;
    	      this.valueMappings = defaults.valueMappings;
        }

        @CustomType.Setter
        public Builder filters(List<DerivedLabelMetricLabelMappingLabelNameMappingFilter> filters) {
            if (filters == null) {
              throw new MissingRequiredPropertyException("DerivedLabelMetricLabelMappingLabelNameMapping", "filters");
            }
            this.filters = filters;
            return this;
        }
        public Builder filters(DerivedLabelMetricLabelMappingLabelNameMappingFilter... filters) {
            return filters(List.of(filters));
        }
        @CustomType.Setter
        public Builder sourceLabel(String sourceLabel) {
            if (sourceLabel == null) {
              throw new MissingRequiredPropertyException("DerivedLabelMetricLabelMappingLabelNameMapping", "sourceLabel");
            }
            this.sourceLabel = sourceLabel;
            return this;
        }
        @CustomType.Setter
        public Builder valueMappings(@Nullable List<DerivedLabelMetricLabelMappingLabelNameMappingValueMapping> valueMappings) {

            this.valueMappings = valueMappings;
            return this;
        }
        public Builder valueMappings(DerivedLabelMetricLabelMappingLabelNameMappingValueMapping... valueMappings) {
            return valueMappings(List.of(valueMappings));
        }
        public DerivedLabelMetricLabelMappingLabelNameMapping build() {
            final var _resultValue = new DerivedLabelMetricLabelMappingLabelNameMapping();
            _resultValue.filters = filters;
            _resultValue.sourceLabel = sourceLabel;
            _resultValue.valueMappings = valueMappings;
            return _resultValue;
        }
    }
}
