// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Double;
import java.util.Objects;

@CustomType
public final class DropRuleValueBasedDrop {
    private Double targetDropValue;

    private DropRuleValueBasedDrop() {}
    public Double targetDropValue() {
        return this.targetDropValue;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DropRuleValueBasedDrop defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Double targetDropValue;
        public Builder() {}
        public Builder(DropRuleValueBasedDrop defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.targetDropValue = defaults.targetDropValue;
        }

        @CustomType.Setter
        public Builder targetDropValue(Double targetDropValue) {
            this.targetDropValue = Objects.requireNonNull(targetDropValue);
            return this;
        }
        public DropRuleValueBasedDrop build() {
            final var o = new DropRuleValueBasedDrop();
            o.targetDropValue = targetDropValue;
            return o;
        }
    }
}
