// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.outputs;

import com.pulumi.core.annotations.CustomType;
import io.chronosphere.chronosphere.outputs.LogControlConfigRuleParseFieldDestination;
import io.chronosphere.chronosphere.outputs.LogControlConfigRuleParseFieldParser;
import io.chronosphere.chronosphere.outputs.LogControlConfigRuleParseFieldSource;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class LogControlConfigRuleParseField {
    private @Nullable LogControlConfigRuleParseFieldDestination destination;
    private LogControlConfigRuleParseFieldParser parser;
    private @Nullable LogControlConfigRuleParseFieldSource source;

    private LogControlConfigRuleParseField() {}
    public Optional<LogControlConfigRuleParseFieldDestination> destination() {
        return Optional.ofNullable(this.destination);
    }
    public LogControlConfigRuleParseFieldParser parser() {
        return this.parser;
    }
    public Optional<LogControlConfigRuleParseFieldSource> source() {
        return Optional.ofNullable(this.source);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LogControlConfigRuleParseField defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable LogControlConfigRuleParseFieldDestination destination;
        private LogControlConfigRuleParseFieldParser parser;
        private @Nullable LogControlConfigRuleParseFieldSource source;
        public Builder() {}
        public Builder(LogControlConfigRuleParseField defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.destination = defaults.destination;
    	      this.parser = defaults.parser;
    	      this.source = defaults.source;
        }

        @CustomType.Setter
        public Builder destination(@Nullable LogControlConfigRuleParseFieldDestination destination) {
            this.destination = destination;
            return this;
        }
        @CustomType.Setter
        public Builder parser(LogControlConfigRuleParseFieldParser parser) {
            this.parser = Objects.requireNonNull(parser);
            return this;
        }
        @CustomType.Setter
        public Builder source(@Nullable LogControlConfigRuleParseFieldSource source) {
            this.source = source;
            return this;
        }
        public LogControlConfigRuleParseField build() {
            final var o = new LogControlConfigRuleParseField();
            o.destination = destination;
            o.parser = parser;
            o.source = source;
            return o;
        }
    }
}
