// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class LogControlConfigRuleReplaceFieldStaticValue {
    /**
     * @return Replacement value. If empty, the matched content is removed.
     * 
     */
    private @Nullable String value;

    private LogControlConfigRuleReplaceFieldStaticValue() {}
    /**
     * @return Replacement value. If empty, the matched content is removed.
     * 
     */
    public Optional<String> value() {
        return Optional.ofNullable(this.value);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LogControlConfigRuleReplaceFieldStaticValue defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String value;
        public Builder() {}
        public Builder(LogControlConfigRuleReplaceFieldStaticValue defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.value = defaults.value;
        }

        @CustomType.Setter
        public Builder value(@Nullable String value) {

            this.value = value;
            return this;
        }
        public LogControlConfigRuleReplaceFieldStaticValue build() {
            final var _resultValue = new LogControlConfigRuleReplaceFieldStaticValue();
            _resultValue.value = value;
            return _resultValue;
        }
    }
}
