// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.outputs;

import com.pulumi.core.annotations.CustomType;
import io.chronosphere.chronosphere.outputs.LogControlConfigRuleEmitMetricsLabelValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class LogControlConfigRuleEmitMetricsLabel {
    private @Nullable String key;
    private @Nullable LogControlConfigRuleEmitMetricsLabelValue value;

    private LogControlConfigRuleEmitMetricsLabel() {}
    public Optional<String> key() {
        return Optional.ofNullable(this.key);
    }
    public Optional<LogControlConfigRuleEmitMetricsLabelValue> value() {
        return Optional.ofNullable(this.value);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LogControlConfigRuleEmitMetricsLabel defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String key;
        private @Nullable LogControlConfigRuleEmitMetricsLabelValue value;
        public Builder() {}
        public Builder(LogControlConfigRuleEmitMetricsLabel defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.key = defaults.key;
    	      this.value = defaults.value;
        }

        @CustomType.Setter
        public Builder key(@Nullable String key) {
            this.key = key;
            return this;
        }
        @CustomType.Setter
        public Builder value(@Nullable LogControlConfigRuleEmitMetricsLabelValue value) {
            this.value = value;
            return this;
        }
        public LogControlConfigRuleEmitMetricsLabel build() {
            final var o = new LogControlConfigRuleEmitMetricsLabel();
            o.key = key;
            o.value = value;
            return o;
        }
    }
}
