// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.chronosphere.chronosphere.outputs.LogIngestConfigPlaintextParserParser;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class LogIngestConfigPlaintextParser {
    /**
     * @return If `true`, the original log is retained after parsing and stored under the `plaintextLog` key. Defaults to `false`.
     * 
     */
    private @Nullable Boolean keepOriginal;
    /**
     * @return Mode that controls how the parser matches incoming plaintext logs.
     * 
     */
    private @Nullable String mode;
    /**
     * @return Name of the parser. Must be unique within the configuration.
     * 
     */
    private String name;
    /**
     * @return Parser configuration. Exactly one of `regexParser`, `keyValueParser`, or `grokParser` must be set, matching `parserType`.
     * 
     */
    private LogIngestConfigPlaintextParserParser parser;

    private LogIngestConfigPlaintextParser() {}
    /**
     * @return If `true`, the original log is retained after parsing and stored under the `plaintextLog` key. Defaults to `false`.
     * 
     */
    public Optional<Boolean> keepOriginal() {
        return Optional.ofNullable(this.keepOriginal);
    }
    /**
     * @return Mode that controls how the parser matches incoming plaintext logs.
     * 
     */
    public Optional<String> mode() {
        return Optional.ofNullable(this.mode);
    }
    /**
     * @return Name of the parser. Must be unique within the configuration.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Parser configuration. Exactly one of `regexParser`, `keyValueParser`, or `grokParser` must be set, matching `parserType`.
     * 
     */
    public LogIngestConfigPlaintextParserParser parser() {
        return this.parser;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LogIngestConfigPlaintextParser defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean keepOriginal;
        private @Nullable String mode;
        private String name;
        private LogIngestConfigPlaintextParserParser parser;
        public Builder() {}
        public Builder(LogIngestConfigPlaintextParser defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.keepOriginal = defaults.keepOriginal;
    	      this.mode = defaults.mode;
    	      this.name = defaults.name;
    	      this.parser = defaults.parser;
        }

        @CustomType.Setter
        public Builder keepOriginal(@Nullable Boolean keepOriginal) {

            this.keepOriginal = keepOriginal;
            return this;
        }
        @CustomType.Setter
        public Builder mode(@Nullable String mode) {

            this.mode = mode;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("LogIngestConfigPlaintextParser", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder parser(LogIngestConfigPlaintextParserParser parser) {
            if (parser == null) {
              throw new MissingRequiredPropertyException("LogIngestConfigPlaintextParser", "parser");
            }
            this.parser = parser;
            return this;
        }
        public LogIngestConfigPlaintextParser build() {
            final var _resultValue = new LogIngestConfigPlaintextParser();
            _resultValue.keepOriginal = keepOriginal;
            _resultValue.mode = mode;
            _resultValue.name = name;
            _resultValue.parser = parser;
            return _resultValue;
        }
    }
}
