// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.outputs;

import com.pulumi.core.annotations.CustomType;
import io.chronosphere.chronosphere.outputs.LogIngestConfigPlaintextParserParserKeyValueParser;
import io.chronosphere.chronosphere.outputs.LogIngestConfigPlaintextParserParserRegexParser;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class LogIngestConfigPlaintextParserParser {
    private @Nullable LogIngestConfigPlaintextParserParserKeyValueParser keyValueParser;
    private String parserType;
    private @Nullable LogIngestConfigPlaintextParserParserRegexParser regexParser;

    private LogIngestConfigPlaintextParserParser() {}
    public Optional<LogIngestConfigPlaintextParserParserKeyValueParser> keyValueParser() {
        return Optional.ofNullable(this.keyValueParser);
    }
    public String parserType() {
        return this.parserType;
    }
    public Optional<LogIngestConfigPlaintextParserParserRegexParser> regexParser() {
        return Optional.ofNullable(this.regexParser);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LogIngestConfigPlaintextParserParser defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable LogIngestConfigPlaintextParserParserKeyValueParser keyValueParser;
        private String parserType;
        private @Nullable LogIngestConfigPlaintextParserParserRegexParser regexParser;
        public Builder() {}
        public Builder(LogIngestConfigPlaintextParserParser defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.keyValueParser = defaults.keyValueParser;
    	      this.parserType = defaults.parserType;
    	      this.regexParser = defaults.regexParser;
        }

        @CustomType.Setter
        public Builder keyValueParser(@Nullable LogIngestConfigPlaintextParserParserKeyValueParser keyValueParser) {
            this.keyValueParser = keyValueParser;
            return this;
        }
        @CustomType.Setter
        public Builder parserType(String parserType) {
            this.parserType = Objects.requireNonNull(parserType);
            return this;
        }
        @CustomType.Setter
        public Builder regexParser(@Nullable LogIngestConfigPlaintextParserParserRegexParser regexParser) {
            this.regexParser = regexParser;
            return this;
        }
        public LogIngestConfigPlaintextParserParser build() {
            final var o = new LogIngestConfigPlaintextParserParser();
            o.keyValueParser = keyValueParser;
            o.parserType = parserType;
            o.regexParser = regexParser;
            return o;
        }
    }
}
