// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class LogscaleActionPagerDutyAction {
    /**
     * @return Routing key used to authenticate with PagerDuty.
     * 
     */
    private String routingKey;
    /**
     * @return Severity attached to the PagerDuty event.
     * 
     */
    private String severity;
    /**
     * @return If `true`, sends the request through the configured outbound proxy.
     * 
     */
    private @Nullable Boolean useProxy;

    private LogscaleActionPagerDutyAction() {}
    /**
     * @return Routing key used to authenticate with PagerDuty.
     * 
     */
    public String routingKey() {
        return this.routingKey;
    }
    /**
     * @return Severity attached to the PagerDuty event.
     * 
     */
    public String severity() {
        return this.severity;
    }
    /**
     * @return If `true`, sends the request through the configured outbound proxy.
     * 
     */
    public Optional<Boolean> useProxy() {
        return Optional.ofNullable(this.useProxy);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LogscaleActionPagerDutyAction defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String routingKey;
        private String severity;
        private @Nullable Boolean useProxy;
        public Builder() {}
        public Builder(LogscaleActionPagerDutyAction defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.routingKey = defaults.routingKey;
    	      this.severity = defaults.severity;
    	      this.useProxy = defaults.useProxy;
        }

        @CustomType.Setter
        public Builder routingKey(String routingKey) {
            if (routingKey == null) {
              throw new MissingRequiredPropertyException("LogscaleActionPagerDutyAction", "routingKey");
            }
            this.routingKey = routingKey;
            return this;
        }
        @CustomType.Setter
        public Builder severity(String severity) {
            if (severity == null) {
              throw new MissingRequiredPropertyException("LogscaleActionPagerDutyAction", "severity");
            }
            this.severity = severity;
            return this;
        }
        @CustomType.Setter
        public Builder useProxy(@Nullable Boolean useProxy) {

            this.useProxy = useProxy;
            return this;
        }
        public LogscaleActionPagerDutyAction build() {
            final var _resultValue = new LogscaleActionPagerDutyAction();
            _resultValue.routingKey = routingKey;
            _resultValue.severity = severity;
            _resultValue.useProxy = useProxy;
            return _resultValue;
        }
    }
}
