// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.outputs;

import com.pulumi.core.annotations.CustomType;
import io.chronosphere.chronosphere.outputs.SLOSliEndpointAvailabilityAdditionalPromqlFilter;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class SLOSliEndpointAvailability {
    private @Nullable List<SLOSliEndpointAvailabilityAdditionalPromqlFilter> additionalPromqlFilters;
    private List<String> endpointsMonitoreds;
    private @Nullable List<String> errorCodes;
    private @Nullable List<String> successCodes;

    private SLOSliEndpointAvailability() {}
    public List<SLOSliEndpointAvailabilityAdditionalPromqlFilter> additionalPromqlFilters() {
        return this.additionalPromqlFilters == null ? List.of() : this.additionalPromqlFilters;
    }
    public List<String> endpointsMonitoreds() {
        return this.endpointsMonitoreds;
    }
    public List<String> errorCodes() {
        return this.errorCodes == null ? List.of() : this.errorCodes;
    }
    public List<String> successCodes() {
        return this.successCodes == null ? List.of() : this.successCodes;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SLOSliEndpointAvailability defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<SLOSliEndpointAvailabilityAdditionalPromqlFilter> additionalPromqlFilters;
        private List<String> endpointsMonitoreds;
        private @Nullable List<String> errorCodes;
        private @Nullable List<String> successCodes;
        public Builder() {}
        public Builder(SLOSliEndpointAvailability defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.additionalPromqlFilters = defaults.additionalPromqlFilters;
    	      this.endpointsMonitoreds = defaults.endpointsMonitoreds;
    	      this.errorCodes = defaults.errorCodes;
    	      this.successCodes = defaults.successCodes;
        }

        @CustomType.Setter
        public Builder additionalPromqlFilters(@Nullable List<SLOSliEndpointAvailabilityAdditionalPromqlFilter> additionalPromqlFilters) {
            this.additionalPromqlFilters = additionalPromqlFilters;
            return this;
        }
        public Builder additionalPromqlFilters(SLOSliEndpointAvailabilityAdditionalPromqlFilter... additionalPromqlFilters) {
            return additionalPromqlFilters(List.of(additionalPromqlFilters));
        }
        @CustomType.Setter
        public Builder endpointsMonitoreds(List<String> endpointsMonitoreds) {
            this.endpointsMonitoreds = Objects.requireNonNull(endpointsMonitoreds);
            return this;
        }
        public Builder endpointsMonitoreds(String... endpointsMonitoreds) {
            return endpointsMonitoreds(List.of(endpointsMonitoreds));
        }
        @CustomType.Setter
        public Builder errorCodes(@Nullable List<String> errorCodes) {
            this.errorCodes = errorCodes;
            return this;
        }
        public Builder errorCodes(String... errorCodes) {
            return errorCodes(List.of(errorCodes));
        }
        @CustomType.Setter
        public Builder successCodes(@Nullable List<String> successCodes) {
            this.successCodes = successCodes;
            return this;
        }
        public Builder successCodes(String... successCodes) {
            return successCodes(List.of(successCodes));
        }
        public SLOSliEndpointAvailability build() {
            final var o = new SLOSliEndpointAvailability();
            o.additionalPromqlFilters = additionalPromqlFilters;
            o.endpointsMonitoreds = endpointsMonitoreds;
            o.errorCodes = errorCodes;
            o.successCodes = successCodes;
            return o;
        }
    }
}
