# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'CollectionDataSourceResult',
    'AwaitableCollectionDataSourceResult',
    'collection_data_source',
    'collection_data_source_output',
]

@pulumi.output_type
class CollectionDataSourceResult:
    """
    A collection of values returned by CollectionDataSource.
    """
    def __init__(__self__, description=None, id=None, name=None, slug=None):
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if slug and not isinstance(slug, str):
            raise TypeError("Expected argument 'slug' to be a str")
        pulumi.set(__self__, "slug", slug)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        Read-only: free-form description of the collection.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Read-only: display name of the collection.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> Optional[_builtins.str]:
        """
        Slug of the collection to look up.
        """
        return pulumi.get(self, "slug")


class AwaitableCollectionDataSourceResult(CollectionDataSourceResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return CollectionDataSourceResult(
            description=self.description,
            id=self.id,
            name=self.name,
            slug=self.slug)


def collection_data_source(slug: Optional[_builtins.str] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableCollectionDataSourceResult:
    """
    Read-only data source that retrieves an existing collection by slug. References collections created outside of Terraform.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_chronosphere as chronosphere

    default = chronosphere.collection_data_source(slug="default")
    ```


    :param _builtins.str slug: Slug of the collection to look up.
    """
    __args__ = dict()
    __args__['slug'] = slug
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('chronosphere:index/collectionDataSource:CollectionDataSource', __args__, opts=opts, typ=CollectionDataSourceResult).value

    return AwaitableCollectionDataSourceResult(
        description=pulumi.get(__ret__, 'description'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        slug=pulumi.get(__ret__, 'slug'))
def collection_data_source_output(slug: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[CollectionDataSourceResult]:
    """
    Read-only data source that retrieves an existing collection by slug. References collections created outside of Terraform.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_chronosphere as chronosphere

    default = chronosphere.collection_data_source(slug="default")
    ```


    :param _builtins.str slug: Slug of the collection to look up.
    """
    __args__ = dict()
    __args__['slug'] = slug
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('chronosphere:index/collectionDataSource:CollectionDataSource', __args__, opts=opts, typ=CollectionDataSourceResult)
    return __ret__.apply(lambda __response__: CollectionDataSourceResult(
        description=pulumi.get(__response__, 'description'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        slug=pulumi.get(__response__, 'slug')))
