# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['RecordingRuleArgs', 'RecordingRule']

@pulumi.input_type
class RecordingRuleArgs:
    def __init__(__self__, *,
                 expr: pulumi.Input[str],
                 name: pulumi.Input[str],
                 bucket_id: Optional[pulumi.Input[str]] = None,
                 execution_group: Optional[pulumi.Input[str]] = None,
                 execution_mode: Optional[pulumi.Input[str]] = None,
                 interval: Optional[pulumi.Input[str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 metric_name: Optional[pulumi.Input[str]] = None,
                 slug: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a RecordingRule resource.
        :param pulumi.Input[str] expr: PromQL expression evaluated at each interval. The result is written to a new series named by `metric_name` (or `name` if unset).
        :param pulumi.Input[str] name: Display name of the recording rule. Can be changed after creation.
        :param pulumi.Input[str] bucket_id: ID of the bucket the recording rule belongs to. At least one of `bucket_id` or `execution_group` must be set; if both are set their values must match.
        :param pulumi.Input[str] execution_group: Slug of the execution group in which the rule is evaluated. Rules in the same group run sequentially at the configured interval; all rules in a group must finish before the next iteration starts. At least one of `bucket_id` or `execution_group` must be set.
        :param pulumi.Input[str] execution_mode: Execution mode controlling whether the recording rule is active.
        :param pulumi.Input[str] interval: Evaluation interval (e.g. `30s`, `1m`). Defaults to `60s` when unset.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] labels: Key/value labels added to every series produced by this recording rule.
        :param pulumi.Input[str] metric_name: Name of the output time series produced by `expr`. Must be a valid metric name. Defaults to `name` if omitted.
        :param pulumi.Input[str] slug: Stable identifier for the recording rule. Generated from `name` if omitted. Immutable after creation.
        """
        pulumi.set(__self__, "expr", expr)
        pulumi.set(__self__, "name", name)
        if bucket_id is not None:
            pulumi.set(__self__, "bucket_id", bucket_id)
        if execution_group is not None:
            pulumi.set(__self__, "execution_group", execution_group)
        if execution_mode is not None:
            pulumi.set(__self__, "execution_mode", execution_mode)
        if interval is not None:
            pulumi.set(__self__, "interval", interval)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if metric_name is not None:
            pulumi.set(__self__, "metric_name", metric_name)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)

    @property
    @pulumi.getter
    def expr(self) -> pulumi.Input[str]:
        """
        PromQL expression evaluated at each interval. The result is written to a new series named by `metric_name` (or `name` if unset).
        """
        return pulumi.get(self, "expr")

    @expr.setter
    def expr(self, value: pulumi.Input[str]):
        pulumi.set(self, "expr", value)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        """
        Display name of the recording rule. Can be changed after creation.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="bucketId")
    def bucket_id(self) -> Optional[pulumi.Input[str]]:
        """
        ID of the bucket the recording rule belongs to. At least one of `bucket_id` or `execution_group` must be set; if both are set their values must match.
        """
        return pulumi.get(self, "bucket_id")

    @bucket_id.setter
    def bucket_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "bucket_id", value)

    @property
    @pulumi.getter(name="executionGroup")
    def execution_group(self) -> Optional[pulumi.Input[str]]:
        """
        Slug of the execution group in which the rule is evaluated. Rules in the same group run sequentially at the configured interval; all rules in a group must finish before the next iteration starts. At least one of `bucket_id` or `execution_group` must be set.
        """
        return pulumi.get(self, "execution_group")

    @execution_group.setter
    def execution_group(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "execution_group", value)

    @property
    @pulumi.getter(name="executionMode")
    def execution_mode(self) -> Optional[pulumi.Input[str]]:
        """
        Execution mode controlling whether the recording rule is active.
        """
        return pulumi.get(self, "execution_mode")

    @execution_mode.setter
    def execution_mode(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "execution_mode", value)

    @property
    @pulumi.getter
    def interval(self) -> Optional[pulumi.Input[str]]:
        """
        Evaluation interval (e.g. `30s`, `1m`). Defaults to `60s` when unset.
        """
        return pulumi.get(self, "interval")

    @interval.setter
    def interval(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "interval", value)

    @property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        Key/value labels added to every series produced by this recording rule.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "labels", value)

    @property
    @pulumi.getter(name="metricName")
    def metric_name(self) -> Optional[pulumi.Input[str]]:
        """
        Name of the output time series produced by `expr`. Must be a valid metric name. Defaults to `name` if omitted.
        """
        return pulumi.get(self, "metric_name")

    @metric_name.setter
    def metric_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "metric_name", value)

    @property
    @pulumi.getter
    def slug(self) -> Optional[pulumi.Input[str]]:
        """
        Stable identifier for the recording rule. Generated from `name` if omitted. Immutable after creation.
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "slug", value)


@pulumi.input_type
class _RecordingRuleState:
    def __init__(__self__, *,
                 bucket_id: Optional[pulumi.Input[str]] = None,
                 execution_group: Optional[pulumi.Input[str]] = None,
                 execution_mode: Optional[pulumi.Input[str]] = None,
                 expr: Optional[pulumi.Input[str]] = None,
                 interval: Optional[pulumi.Input[str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 metric_name: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 slug: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering RecordingRule resources.
        :param pulumi.Input[str] bucket_id: ID of the bucket the recording rule belongs to. At least one of `bucket_id` or `execution_group` must be set; if both are set their values must match.
        :param pulumi.Input[str] execution_group: Slug of the execution group in which the rule is evaluated. Rules in the same group run sequentially at the configured interval; all rules in a group must finish before the next iteration starts. At least one of `bucket_id` or `execution_group` must be set.
        :param pulumi.Input[str] execution_mode: Execution mode controlling whether the recording rule is active.
        :param pulumi.Input[str] expr: PromQL expression evaluated at each interval. The result is written to a new series named by `metric_name` (or `name` if unset).
        :param pulumi.Input[str] interval: Evaluation interval (e.g. `30s`, `1m`). Defaults to `60s` when unset.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] labels: Key/value labels added to every series produced by this recording rule.
        :param pulumi.Input[str] metric_name: Name of the output time series produced by `expr`. Must be a valid metric name. Defaults to `name` if omitted.
        :param pulumi.Input[str] name: Display name of the recording rule. Can be changed after creation.
        :param pulumi.Input[str] slug: Stable identifier for the recording rule. Generated from `name` if omitted. Immutable after creation.
        """
        if bucket_id is not None:
            pulumi.set(__self__, "bucket_id", bucket_id)
        if execution_group is not None:
            pulumi.set(__self__, "execution_group", execution_group)
        if execution_mode is not None:
            pulumi.set(__self__, "execution_mode", execution_mode)
        if expr is not None:
            pulumi.set(__self__, "expr", expr)
        if interval is not None:
            pulumi.set(__self__, "interval", interval)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if metric_name is not None:
            pulumi.set(__self__, "metric_name", metric_name)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)

    @property
    @pulumi.getter(name="bucketId")
    def bucket_id(self) -> Optional[pulumi.Input[str]]:
        """
        ID of the bucket the recording rule belongs to. At least one of `bucket_id` or `execution_group` must be set; if both are set their values must match.
        """
        return pulumi.get(self, "bucket_id")

    @bucket_id.setter
    def bucket_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "bucket_id", value)

    @property
    @pulumi.getter(name="executionGroup")
    def execution_group(self) -> Optional[pulumi.Input[str]]:
        """
        Slug of the execution group in which the rule is evaluated. Rules in the same group run sequentially at the configured interval; all rules in a group must finish before the next iteration starts. At least one of `bucket_id` or `execution_group` must be set.
        """
        return pulumi.get(self, "execution_group")

    @execution_group.setter
    def execution_group(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "execution_group", value)

    @property
    @pulumi.getter(name="executionMode")
    def execution_mode(self) -> Optional[pulumi.Input[str]]:
        """
        Execution mode controlling whether the recording rule is active.
        """
        return pulumi.get(self, "execution_mode")

    @execution_mode.setter
    def execution_mode(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "execution_mode", value)

    @property
    @pulumi.getter
    def expr(self) -> Optional[pulumi.Input[str]]:
        """
        PromQL expression evaluated at each interval. The result is written to a new series named by `metric_name` (or `name` if unset).
        """
        return pulumi.get(self, "expr")

    @expr.setter
    def expr(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "expr", value)

    @property
    @pulumi.getter
    def interval(self) -> Optional[pulumi.Input[str]]:
        """
        Evaluation interval (e.g. `30s`, `1m`). Defaults to `60s` when unset.
        """
        return pulumi.get(self, "interval")

    @interval.setter
    def interval(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "interval", value)

    @property
    @pulumi.getter
    def labels(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        """
        Key/value labels added to every series produced by this recording rule.
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "labels", value)

    @property
    @pulumi.getter(name="metricName")
    def metric_name(self) -> Optional[pulumi.Input[str]]:
        """
        Name of the output time series produced by `expr`. Must be a valid metric name. Defaults to `name` if omitted.
        """
        return pulumi.get(self, "metric_name")

    @metric_name.setter
    def metric_name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "metric_name", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Display name of the recording rule. Can be changed after creation.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def slug(self) -> Optional[pulumi.Input[str]]:
        """
        Stable identifier for the recording rule. Generated from `name` if omitted. Immutable after creation.
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "slug", value)


class RecordingRule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 bucket_id: Optional[pulumi.Input[str]] = None,
                 execution_group: Optional[pulumi.Input[str]] = None,
                 execution_mode: Optional[pulumi.Input[str]] = None,
                 expr: Optional[pulumi.Input[str]] = None,
                 interval: Optional[pulumi.Input[str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 metric_name: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 slug: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Evaluates a PromQL expression at a fixed interval and writes the result to a new time series. Useful for precomputing expensive queries or producing derived metrics.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_chronosphere as chronosphere

        up_by_namespace = chronosphere.RecordingRule("upByNamespace",
            expr="sum by (kubernetes_namespace) (up)",
            interval="60s",
            labels={
                "owner": "platform",
            },
            metric_name="up:by_namespace",
            name="up:by_namespace")
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] bucket_id: ID of the bucket the recording rule belongs to. At least one of `bucket_id` or `execution_group` must be set; if both are set their values must match.
        :param pulumi.Input[str] execution_group: Slug of the execution group in which the rule is evaluated. Rules in the same group run sequentially at the configured interval; all rules in a group must finish before the next iteration starts. At least one of `bucket_id` or `execution_group` must be set.
        :param pulumi.Input[str] execution_mode: Execution mode controlling whether the recording rule is active.
        :param pulumi.Input[str] expr: PromQL expression evaluated at each interval. The result is written to a new series named by `metric_name` (or `name` if unset).
        :param pulumi.Input[str] interval: Evaluation interval (e.g. `30s`, `1m`). Defaults to `60s` when unset.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] labels: Key/value labels added to every series produced by this recording rule.
        :param pulumi.Input[str] metric_name: Name of the output time series produced by `expr`. Must be a valid metric name. Defaults to `name` if omitted.
        :param pulumi.Input[str] name: Display name of the recording rule. Can be changed after creation.
        :param pulumi.Input[str] slug: Stable identifier for the recording rule. Generated from `name` if omitted. Immutable after creation.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RecordingRuleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Evaluates a PromQL expression at a fixed interval and writes the result to a new time series. Useful for precomputing expensive queries or producing derived metrics.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_chronosphere as chronosphere

        up_by_namespace = chronosphere.RecordingRule("upByNamespace",
            expr="sum by (kubernetes_namespace) (up)",
            interval="60s",
            labels={
                "owner": "platform",
            },
            metric_name="up:by_namespace",
            name="up:by_namespace")
        ```

        :param str resource_name: The name of the resource.
        :param RecordingRuleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RecordingRuleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 bucket_id: Optional[pulumi.Input[str]] = None,
                 execution_group: Optional[pulumi.Input[str]] = None,
                 execution_mode: Optional[pulumi.Input[str]] = None,
                 expr: Optional[pulumi.Input[str]] = None,
                 interval: Optional[pulumi.Input[str]] = None,
                 labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 metric_name: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 slug: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RecordingRuleArgs.__new__(RecordingRuleArgs)

            __props__.__dict__["bucket_id"] = bucket_id
            __props__.__dict__["execution_group"] = execution_group
            __props__.__dict__["execution_mode"] = execution_mode
            if expr is None and not opts.urn:
                raise TypeError("Missing required property 'expr'")
            __props__.__dict__["expr"] = expr
            __props__.__dict__["interval"] = interval
            __props__.__dict__["labels"] = labels
            __props__.__dict__["metric_name"] = metric_name
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["slug"] = slug
        super(RecordingRule, __self__).__init__(
            'chronosphere:index/recordingRule:RecordingRule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            bucket_id: Optional[pulumi.Input[str]] = None,
            execution_group: Optional[pulumi.Input[str]] = None,
            execution_mode: Optional[pulumi.Input[str]] = None,
            expr: Optional[pulumi.Input[str]] = None,
            interval: Optional[pulumi.Input[str]] = None,
            labels: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
            metric_name: Optional[pulumi.Input[str]] = None,
            name: Optional[pulumi.Input[str]] = None,
            slug: Optional[pulumi.Input[str]] = None) -> 'RecordingRule':
        """
        Get an existing RecordingRule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] bucket_id: ID of the bucket the recording rule belongs to. At least one of `bucket_id` or `execution_group` must be set; if both are set their values must match.
        :param pulumi.Input[str] execution_group: Slug of the execution group in which the rule is evaluated. Rules in the same group run sequentially at the configured interval; all rules in a group must finish before the next iteration starts. At least one of `bucket_id` or `execution_group` must be set.
        :param pulumi.Input[str] execution_mode: Execution mode controlling whether the recording rule is active.
        :param pulumi.Input[str] expr: PromQL expression evaluated at each interval. The result is written to a new series named by `metric_name` (or `name` if unset).
        :param pulumi.Input[str] interval: Evaluation interval (e.g. `30s`, `1m`). Defaults to `60s` when unset.
        :param pulumi.Input[Mapping[str, pulumi.Input[str]]] labels: Key/value labels added to every series produced by this recording rule.
        :param pulumi.Input[str] metric_name: Name of the output time series produced by `expr`. Must be a valid metric name. Defaults to `name` if omitted.
        :param pulumi.Input[str] name: Display name of the recording rule. Can be changed after creation.
        :param pulumi.Input[str] slug: Stable identifier for the recording rule. Generated from `name` if omitted. Immutable after creation.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RecordingRuleState.__new__(_RecordingRuleState)

        __props__.__dict__["bucket_id"] = bucket_id
        __props__.__dict__["execution_group"] = execution_group
        __props__.__dict__["execution_mode"] = execution_mode
        __props__.__dict__["expr"] = expr
        __props__.__dict__["interval"] = interval
        __props__.__dict__["labels"] = labels
        __props__.__dict__["metric_name"] = metric_name
        __props__.__dict__["name"] = name
        __props__.__dict__["slug"] = slug
        return RecordingRule(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="bucketId")
    def bucket_id(self) -> pulumi.Output[Optional[str]]:
        """
        ID of the bucket the recording rule belongs to. At least one of `bucket_id` or `execution_group` must be set; if both are set their values must match.
        """
        return pulumi.get(self, "bucket_id")

    @property
    @pulumi.getter(name="executionGroup")
    def execution_group(self) -> pulumi.Output[Optional[str]]:
        """
        Slug of the execution group in which the rule is evaluated. Rules in the same group run sequentially at the configured interval; all rules in a group must finish before the next iteration starts. At least one of `bucket_id` or `execution_group` must be set.
        """
        return pulumi.get(self, "execution_group")

    @property
    @pulumi.getter(name="executionMode")
    def execution_mode(self) -> pulumi.Output[Optional[str]]:
        """
        Execution mode controlling whether the recording rule is active.
        """
        return pulumi.get(self, "execution_mode")

    @property
    @pulumi.getter
    def expr(self) -> pulumi.Output[str]:
        """
        PromQL expression evaluated at each interval. The result is written to a new series named by `metric_name` (or `name` if unset).
        """
        return pulumi.get(self, "expr")

    @property
    @pulumi.getter
    def interval(self) -> pulumi.Output[Optional[str]]:
        """
        Evaluation interval (e.g. `30s`, `1m`). Defaults to `60s` when unset.
        """
        return pulumi.get(self, "interval")

    @property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Optional[Mapping[str, str]]]:
        """
        Key/value labels added to every series produced by this recording rule.
        """
        return pulumi.get(self, "labels")

    @property
    @pulumi.getter(name="metricName")
    def metric_name(self) -> pulumi.Output[Optional[str]]:
        """
        Name of the output time series produced by `expr`. Must be a valid metric name. Defaults to `name` if omitted.
        """
        return pulumi.get(self, "metric_name")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        Display name of the recording rule. Can be changed after creation.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def slug(self) -> pulumi.Output[str]:
        """
        Stable identifier for the recording rule. Generated from `name` if omitted. Immutable after creation.
        """
        return pulumi.get(self, "slug")

