// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Chronosphere.Inputs
{

    public sealed class SlackAlertNotifierFieldGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("short")]
        public Input<bool>? Short { get; set; }

        [Input("title")]
        public Input<string>? Title { get; set; }

        [Input("value")]
        public Input<string>? Value { get; set; }

        public SlackAlertNotifierFieldGetArgs()
        {
        }
        public static new SlackAlertNotifierFieldGetArgs Empty => new SlackAlertNotifierFieldGetArgs();
    }
}
