// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.chronosphere.chronosphere.PagerdutyExternalConnectionArgs;
import io.chronosphere.chronosphere.Utilities;
import io.chronosphere.chronosphere.inputs.PagerdutyExternalConnectionState;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="chronosphere:index/pagerdutyExternalConnection:PagerdutyExternalConnection")
public class PagerdutyExternalConnection extends com.pulumi.resources.CustomResource {
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="pagerdutyApiKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> pagerdutyApiKey;

    public Output<Optional<String>> pagerdutyApiKey() {
        return Codegen.optional(this.pagerdutyApiKey);
    }
    @Export(name="pagerdutyEventsVersion", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> pagerdutyEventsVersion;

    public Output<Optional<String>> pagerdutyEventsVersion() {
        return Codegen.optional(this.pagerdutyEventsVersion);
    }
    @Export(name="pagerdutyRestApiKey", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> pagerdutyRestApiKey;

    public Output<Optional<String>> pagerdutyRestApiKey() {
        return Codegen.optional(this.pagerdutyRestApiKey);
    }
    @Export(name="slug", refs={String.class}, tree="[0]")
    private Output<String> slug;

    public Output<String> slug() {
        return this.slug;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public PagerdutyExternalConnection(String name) {
        this(name, PagerdutyExternalConnectionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public PagerdutyExternalConnection(String name, PagerdutyExternalConnectionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public PagerdutyExternalConnection(String name, PagerdutyExternalConnectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("chronosphere:index/pagerdutyExternalConnection:PagerdutyExternalConnection", name, args == null ? PagerdutyExternalConnectionArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private PagerdutyExternalConnection(String name, Output<String> id, @Nullable PagerdutyExternalConnectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("chronosphere:index/pagerdutyExternalConnection:PagerdutyExternalConnection", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "pagerdutyApiKey",
                "pagerdutyRestApiKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static PagerdutyExternalConnection get(String name, Output<String> id, @Nullable PagerdutyExternalConnectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new PagerdutyExternalConnection(name, id, state, options);
    }
}
