// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.chronosphere.chronosphere.ResourcePoolsConfigArgs;
import io.chronosphere.chronosphere.Utilities;
import io.chronosphere.chronosphere.inputs.ResourcePoolsConfigState;
import io.chronosphere.chronosphere.outputs.ResourcePoolsConfigDefaultPool;
import io.chronosphere.chronosphere.outputs.ResourcePoolsConfigPool;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="chronosphere:index/resourcePoolsConfig:ResourcePoolsConfig")
public class ResourcePoolsConfig extends com.pulumi.resources.CustomResource {
    @Export(name="defaultPool", refs={ResourcePoolsConfigDefaultPool.class}, tree="[0]")
    private Output</* @Nullable */ ResourcePoolsConfigDefaultPool> defaultPool;

    public Output<Optional<ResourcePoolsConfigDefaultPool>> defaultPool() {
        return Codegen.optional(this.defaultPool);
    }
    @Export(name="pool", refs={List.class,ResourcePoolsConfigPool.class}, tree="[0,1]")
    private Output</* @Nullable */ List<ResourcePoolsConfigPool>> pool;

    public Output<Optional<List<ResourcePoolsConfigPool>>> pool() {
        return Codegen.optional(this.pool);
    }
    /**
     * @deprecated
     * Use pool instead of pools
     * 
     */
    @Deprecated /* Use pool instead of pools */
    @Export(name="pools", refs={List.class,ResourcePoolsConfigPool.class}, tree="[0,1]")
    private Output</* @Nullable */ List<ResourcePoolsConfigPool>> pools;

    public Output<Optional<List<ResourcePoolsConfigPool>>> pools() {
        return Codegen.optional(this.pools);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ResourcePoolsConfig(String name) {
        this(name, ResourcePoolsConfigArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ResourcePoolsConfig(String name, @Nullable ResourcePoolsConfigArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ResourcePoolsConfig(String name, @Nullable ResourcePoolsConfigArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("chronosphere:index/resourcePoolsConfig:ResourcePoolsConfig", name, args == null ? ResourcePoolsConfigArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private ResourcePoolsConfig(String name, Output<String> id, @Nullable ResourcePoolsConfigState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("chronosphere:index/resourcePoolsConfig:ResourcePoolsConfig", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ResourcePoolsConfig get(String name, Output<String> id, @Nullable ResourcePoolsConfigState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ResourcePoolsConfig(name, id, state, options);
    }
}
