// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.chronosphere.chronosphere.ServiceAttributeArgs;
import io.chronosphere.chronosphere.Utilities;
import io.chronosphere.chronosphere.inputs.ServiceAttributeState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Associates metadata with an existing service, such as a human-readable name, description, owning team, and default notification policy. The service itself must already exist; this resource only attaches attributes to it.
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.chronosphere.ServiceAttribute;
 * import com.pulumi.chronosphere.ServiceAttributeArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var gateway = new ServiceAttribute(&#34;gateway&#34;, ServiceAttributeArgs.builder()        
 *             .description(&#34;Edge API gateway&#34;)
 *             .name(&#34;Gateway&#34;)
 *             .serviceSlug(&#34;gateway&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 */
@ResourceType(type="chronosphere:index/serviceAttribute:ServiceAttribute")
public class ServiceAttribute extends com.pulumi.resources.CustomResource {
    /**
     * Human-readable description of the service
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Human-readable description of the service
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Name of the service
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> name;

    /**
     * @return Name of the service
     * 
     */
    public Output<Optional<String>> name() {
        return Codegen.optional(this.name);
    }
    /**
     * Notification policy ID for alerts
     * 
     */
    @Export(name="notificationPolicyId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> notificationPolicyId;

    /**
     * @return Notification policy ID for alerts
     * 
     */
    public Output<Optional<String>> notificationPolicyId() {
        return Codegen.optional(this.notificationPolicyId);
    }
    /**
     * The slug of the service to associate attributes with
     * 
     */
    @Export(name="serviceSlug", refs={String.class}, tree="[0]")
    private Output<String> serviceSlug;

    /**
     * @return The slug of the service to associate attributes with
     * 
     */
    public Output<String> serviceSlug() {
        return this.serviceSlug;
    }
    /**
     * Team that owns the service
     * 
     */
    @Export(name="teamId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> teamId;

    /**
     * @return Team that owns the service
     * 
     */
    public Output<Optional<String>> teamId() {
        return Codegen.optional(this.teamId);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ServiceAttribute(String name) {
        this(name, ServiceAttributeArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ServiceAttribute(String name, ServiceAttributeArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ServiceAttribute(String name, ServiceAttributeArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("chronosphere:index/serviceAttribute:ServiceAttribute", name, args == null ? ServiceAttributeArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private ServiceAttribute(String name, Output<String> id, @Nullable ServiceAttributeState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("chronosphere:index/serviceAttribute:ServiceAttribute", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ServiceAttribute get(String name, Output<String> id, @Nullable ServiceAttributeState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ServiceAttribute(name, id, state, options);
    }
}
