// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class ConsumptionBudgetThreshold
    {
        public readonly string? Action;
        public readonly Outputs.ConsumptionBudgetThresholdInstantRate? InstantRate;
        public readonly string? Type;
        public readonly Outputs.ConsumptionBudgetThresholdVolume? Volume;

        [OutputConstructor]
        private ConsumptionBudgetThreshold(
            string? action,

            Outputs.ConsumptionBudgetThresholdInstantRate? instantRate,

            string? type,

            Outputs.ConsumptionBudgetThresholdVolume? volume)
        {
            Action = action;
            InstantRate = instantRate;
            Type = type;
            Volume = volume;
        }
    }
}
