// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class ConsumptionConfigPartitionPartitionPartitionPartitionPartitionFilter
    {
        /// <summary>
        /// Conditions evaluated by the filter. Each condition matches by dataset, logs, metrics, or trace data; exactly one of `LogFilter`, `MetricFilter`, `TraceSpanFilters`, or `DatasetId` must be set per condition.
        /// </summary>
        public readonly ImmutableArray<Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionPartitionFilterCondition> Conditions;
        /// <summary>
        /// Match operator (e.g. `IN`, `NOT_IN`) applied to the filter conditions.
        /// </summary>
        public readonly string? Operator;

        [OutputConstructor]
        private ConsumptionConfigPartitionPartitionPartitionPartitionPartitionFilter(
            ImmutableArray<Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionPartitionFilterCondition> conditions,

            string? @operator)
        {
            Conditions = conditions;
            Operator = @operator;
        }
    }
}
