// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class ConsumptionConfigPartitionPartitionPartition
    {
        public readonly ImmutableArray<Outputs.ConsumptionConfigPartitionPartitionPartitionFilter> Filters;
        public readonly string? Name;
        public readonly ImmutableArray<Outputs.ConsumptionConfigPartitionPartitionPartitionPartition> Partitions;
        public readonly string? Slug;

        [OutputConstructor]
        private ConsumptionConfigPartitionPartitionPartition(
            ImmutableArray<Outputs.ConsumptionConfigPartitionPartitionPartitionFilter> filters,

            string? name,

            ImmutableArray<Outputs.ConsumptionConfigPartitionPartitionPartitionPartition> partitions,

            string? slug)
        {
            Filters = filters;
            Name = name;
            Partitions = partitions;
            Slug = slug;
        }
    }
}
