// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilter
    {
        /// <summary>
        /// Matches traces or spans whose duration in seconds falls within the inclusive `[min_secs, MaxSecs]` range.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterDuration? Duration;
        /// <summary>
        /// Matches traces or spans where the target boolean field equals `Value`.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterError? Error;
        /// <summary>
        /// Matches traces or spans where the target boolean field equals `Value`.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterIsRootSpan? IsRootSpan;
        /// <summary>
        /// Matches traces or spans where the target string field satisfies the match condition.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterOperation? Operation;
        /// <summary>
        /// Matches traces or spans where the target string field satisfies the match condition.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterParentOperation? ParentOperation;
        /// <summary>
        /// Matches traces or spans where the target string field satisfies the match condition.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterParentService? ParentService;
        /// <summary>
        /// Matches traces or spans where the target string field satisfies the match condition.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterService? Service;
        /// <summary>
        /// Matches spans whose tag (span attribute) with the given `Key` has a value satisfying the nested string or numeric filter.
        /// </summary>
        public readonly ImmutableArray<Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterTag> Tags;

        [OutputConstructor]
        private ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilter(
            Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterDuration? duration,

            Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterError? error,

            Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterIsRootSpan? isRootSpan,

            Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterOperation? operation,

            Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterParentOperation? parentOperation,

            Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterParentService? parentService,

            Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterService? service,

            ImmutableArray<Outputs.ConsumptionConfigPartitionPartitionPartitionPartitionFilterConditionTraceSpanFilterTag> tags)
        {
            Duration = duration;
            Error = error;
            IsRootSpan = isRootSpan;
            Operation = operation;
            ParentOperation = parentOperation;
            ParentService = parentService;
            Service = service;
            Tags = tags;
        }
    }
}
