// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class ConsumptionConfigPartitionFilterConditionTraceSpanFilter
    {
        /// <summary>
        /// Matches traces or spans whose duration in seconds falls within the inclusive `[min_secs, MaxSecs]` range.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterDuration? Duration;
        /// <summary>
        /// Matches traces or spans where the target boolean field equals `Value`.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterError? Error;
        /// <summary>
        /// Matches traces or spans where the target boolean field equals `Value`.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterIsRootSpan? IsRootSpan;
        /// <summary>
        /// Matches traces or spans where the target string field satisfies the match condition.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterOperation? Operation;
        /// <summary>
        /// Matches traces or spans where the target string field satisfies the match condition.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentOperation? ParentOperation;
        /// <summary>
        /// Matches traces or spans where the target string field satisfies the match condition.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentService? ParentService;
        /// <summary>
        /// Matches traces or spans where the target string field satisfies the match condition.
        /// </summary>
        public readonly Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterService? Service;
        /// <summary>
        /// Matches spans whose tag (span attribute) with the given `Key` has a value satisfying the nested string or numeric filter.
        /// </summary>
        public readonly ImmutableArray<Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterTag> Tags;

        [OutputConstructor]
        private ConsumptionConfigPartitionFilterConditionTraceSpanFilter(
            Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterDuration? duration,

            Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterError? error,

            Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterIsRootSpan? isRootSpan,

            Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterOperation? operation,

            Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentOperation? parentOperation,

            Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentService? parentService,

            Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterService? service,

            ImmutableArray<Outputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterTag> tags)
        {
            Duration = duration;
            Error = error;
            IsRootSpan = isRootSpan;
            Operation = operation;
            ParentOperation = parentOperation;
            ParentService = parentService;
            Service = service;
            Tags = tags;
        }
    }
}
