// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class ConsumptionBudgetThreshold
    {
        /// <summary>
        /// Action to take when this threshold is exceeded (e.g. drop traffic, fire warning/critical alert).
        /// </summary>
        public readonly string? Action;
        /// <summary>
        /// Configures an instant-rate threshold value. Set when `type` is an instant-rate type.
        /// </summary>
        public readonly Outputs.ConsumptionBudgetThresholdInstantRate? InstantRate;
        /// <summary>
        /// Resource group the threshold applies to (e.g. metrics, logs, traces). Replaces the deprecated top-level `resource` field.
        /// </summary>
        public readonly string? ResourceGroup;
        /// <summary>
        /// SKU group the threshold applies to (e.g. metrics, logs, traces). Replaces the deprecated top-level `resource` field.
        /// </summary>
        public readonly string? SkuGroup;
        /// <summary>
        /// Measurement window over which the threshold is evaluated (e.g. instant rate vs. rolling volume).
        /// </summary>
        public readonly string? Type;
        /// <summary>
        /// Unit in which the threshold value is denominated (e.g. bytes, datapoints).
        /// </summary>
        public readonly string? Unit;
        /// <summary>
        /// Configures a volume threshold value. Set when `type` is a volume type.
        /// </summary>
        public readonly Outputs.ConsumptionBudgetThresholdVolume? Volume;

        [OutputConstructor]
        private ConsumptionBudgetThreshold(
            string? action,

            Outputs.ConsumptionBudgetThresholdInstantRate? instantRate,

            string? resourceGroup,

            string? skuGroup,

            string? type,

            string? unit,

            Outputs.ConsumptionBudgetThresholdVolume? volume)
        {
            Action = action;
            InstantRate = instantRate;
            ResourceGroup = resourceGroup;
            SkuGroup = skuGroup;
            Type = type;
            Unit = unit;
            Volume = volume;
        }
    }
}
