// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class ConsumptionConfigPartition
    {
        public readonly ImmutableArray<Outputs.ConsumptionConfigPartitionFilter> Filters;
        public readonly string? Name;
        public readonly ImmutableArray<Outputs.ConsumptionConfigPartitionPartition> Partitions;
        public readonly string? Slug;

        [OutputConstructor]
        private ConsumptionConfigPartition(
            ImmutableArray<Outputs.ConsumptionConfigPartitionFilter> filters,

            string? name,

            ImmutableArray<Outputs.ConsumptionConfigPartitionPartition> partitions,

            string? slug)
        {
            Filters = filters;
            Name = name;
            Partitions = partitions;
            Slug = slug;
        }
    }
}
