// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class DatasetConfigurationTraceDatasetMatchCriteria
    {
        public readonly Outputs.DatasetConfigurationTraceDatasetMatchCriteriaScopeFilter? ScopeFilter;
        public readonly ImmutableArray<Outputs.DatasetConfigurationTraceDatasetMatchCriteriaSpan> Spans;
        public readonly Outputs.DatasetConfigurationTraceDatasetMatchCriteriaTrace? Trace;

        [OutputConstructor]
        private DatasetConfigurationTraceDatasetMatchCriteria(
            Outputs.DatasetConfigurationTraceDatasetMatchCriteriaScopeFilter? scopeFilter,

            ImmutableArray<Outputs.DatasetConfigurationTraceDatasetMatchCriteriaSpan> spans,

            Outputs.DatasetConfigurationTraceDatasetMatchCriteriaTrace? trace)
        {
            ScopeFilter = scopeFilter;
            Spans = spans;
            Trace = trace;
        }
    }
}
