// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class LogAllocationConfigDatasetAllocationPriorities
    {
        public readonly ImmutableArray<Outputs.LogAllocationConfigDatasetAllocationPrioritiesHighPriorityFilter> HighPriorityFilters;
        public readonly ImmutableArray<Outputs.LogAllocationConfigDatasetAllocationPrioritiesLowPriorityFilter> LowPriorityFilters;

        [OutputConstructor]
        private LogAllocationConfigDatasetAllocationPriorities(
            ImmutableArray<Outputs.LogAllocationConfigDatasetAllocationPrioritiesHighPriorityFilter> highPriorityFilters,

            ImmutableArray<Outputs.LogAllocationConfigDatasetAllocationPrioritiesLowPriorityFilter> lowPriorityFilters)
        {
            HighPriorityFilters = highPriorityFilters;
            LowPriorityFilters = lowPriorityFilters;
        }
    }
}
