// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class LogAllocationConfigDatasetAllocationAllocation
    {
        /// <summary>
        /// Percentage of the tenant's log license to allocate to this dataset, expressed as a number between 0 and 100.
        /// </summary>
        public readonly double PercentOfLicense;

        [OutputConstructor]
        private LogAllocationConfigDatasetAllocationAllocation(double percentOfLicense)
        {
            PercentOfLicense = percentOfLicense;
        }
    }
}
