// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class LogControlConfigRuleReplaceField
    {
        /// <summary>
        /// Path to a field within a log record.
        /// </summary>
        public readonly Outputs.LogControlConfigRuleReplaceFieldField? Field;
        /// <summary>
        /// Replace field values using a key/value lookup table. Exactly one of `MappedValue` or `StaticValue` must be set.
        /// </summary>
        public readonly Outputs.LogControlConfigRuleReplaceFieldMappedValue? MappedValue;
        /// <summary>
        /// If `True`, replaces all matches. If `False`, replaces only the first match.
        /// </summary>
        public readonly bool? ReplaceAll;
        /// <summary>
        /// Mode that controls how the replacement is applied to matched content.
        /// </summary>
        public readonly string? ReplaceMode;
        /// <summary>
        /// Regular expression that selects which part of the field value to replace.
        /// </summary>
        public readonly string? ReplaceRegex;
        /// <summary>
        /// Replace matched content with a static string. Exactly one of `MappedValue` or `StaticValue` must be set.
        /// </summary>
        public readonly Outputs.LogControlConfigRuleReplaceFieldStaticValue? StaticValue;

        [OutputConstructor]
        private LogControlConfigRuleReplaceField(
            Outputs.LogControlConfigRuleReplaceFieldField? field,

            Outputs.LogControlConfigRuleReplaceFieldMappedValue? mappedValue,

            bool? replaceAll,

            string? replaceMode,

            string? replaceRegex,

            Outputs.LogControlConfigRuleReplaceFieldStaticValue? staticValue)
        {
            Field = field;
            MappedValue = mappedValue;
            ReplaceAll = replaceAll;
            ReplaceMode = replaceMode;
            ReplaceRegex = replaceRegex;
            StaticValue = staticValue;
        }
    }
}
