// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class LogControlConfigRuleDropField
    {
        /// <summary>
        /// Regular expression that selects which fields to drop.
        /// </summary>
        public readonly string? FieldRegex;
        /// <summary>
        /// Path to a field within a log record.
        /// </summary>
        public readonly Outputs.LogControlConfigRuleDropFieldParentPath? ParentPath;

        [OutputConstructor]
        private LogControlConfigRuleDropField(
            string? fieldRegex,

            Outputs.LogControlConfigRuleDropFieldParentPath? parentPath)
        {
            FieldRegex = fieldRegex;
            ParentPath = parentPath;
        }
    }
}
