// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class LogscaleActionPagerDutyAction
    {
        /// <summary>
        /// Routing key used to authenticate with PagerDuty.
        /// </summary>
        public readonly string RoutingKey;
        /// <summary>
        /// Severity attached to the PagerDuty event.
        /// </summary>
        public readonly string Severity;
        /// <summary>
        /// If `true`, sends the request through the configured outbound proxy.
        /// </summary>
        public readonly bool? UseProxy;

        [OutputConstructor]
        private LogscaleActionPagerDutyAction(
            string routingKey,

            string severity,

            bool? useProxy)
        {
            RoutingKey = routingKey;
            Severity = severity;
            UseProxy = useProxy;
        }
    }
}
