// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class NotificationPolicyOverrideRouteDestinationWebhookQueryParameter
    {
        /// <summary>
        /// Query parameter name.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// Query parameter value.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private NotificationPolicyOverrideRouteDestinationWebhookQueryParameter(
            string key,

            string value)
        {
            Key = key;
            Value = value;
        }
    }
}
