// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Chronosphere.Outputs
{

    [OutputType]
    public sealed class NotificationPolicyDataSourceOverrideRoute
    {
        public readonly ImmutableArray<string> Notifiers;
        public readonly string? RepeatInterval;
        public readonly string Severity;

        [OutputConstructor]
        private NotificationPolicyDataSourceOverrideRoute(
            ImmutableArray<string> notifiers,

            string? repeatInterval,

            string severity)
        {
            Notifiers = notifiers;
            RepeatInterval = repeatInterval;
            Severity = severity;
        }
    }
}
