// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class SlackAlertNotifierAction
    {
        /// <summary>
        /// Label for the cancel button in the confirmation dialog.
        /// </summary>
        public readonly string? ActionConfirmDismissText;
        /// <summary>
        /// Label for the confirm button in the confirmation dialog.
        /// </summary>
        public readonly string? ActionConfirmOkText;
        /// <summary>
        /// Body text of the confirmation dialog shown before the action runs.
        /// </summary>
        public readonly string? ActionConfirmText;
        /// <summary>
        /// Title of the confirmation dialog shown before the action runs.
        /// </summary>
        public readonly string? ActionConfirmTile;
        /// <summary>
        /// Identifier sent back to Slack when the button is clicked.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Visual style of the button: `Default`, `Primary`, or `Danger`.
        /// </summary>
        public readonly string? Style;
        /// <summary>
        /// Label shown on the button.
        /// </summary>
        public readonly string? Text;
        /// <summary>
        /// Action type. Typically `Button`.
        /// </summary>
        public readonly string? Type;
        /// <summary>
        /// Link the button navigates to when clicked.
        /// </summary>
        public readonly string? Url;
        /// <summary>
        /// Opaque value sent back to Slack alongside `Name` when the button is clicked.
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private SlackAlertNotifierAction(
            string? actionConfirmDismissText,

            string? actionConfirmOkText,

            string? actionConfirmText,

            string? actionConfirmTile,

            string? name,

            string? style,

            string? text,

            string? type,

            string? url,

            string? value)
        {
            ActionConfirmDismissText = actionConfirmDismissText;
            ActionConfirmOkText = actionConfirmOkText;
            ActionConfirmText = actionConfirmText;
            ActionConfirmTile = actionConfirmTile;
            Name = name;
            Style = style;
            Text = text;
            Type = type;
            Url = url;
            Value = value;
        }
    }
}
