// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class SLODefinition
    {
        public readonly bool? LowVolume;
        public readonly double Objective;
        public readonly ImmutableArray<Outputs.SLODefinitionReportingWindow> ReportingWindows;

        [OutputConstructor]
        private SLODefinition(
            bool? lowVolume,

            double objective,

            ImmutableArray<Outputs.SLODefinitionReportingWindow> reportingWindows)
        {
            LowVolume = lowVolume;
            Objective = objective;
            ReportingWindows = reportingWindows;
        }
    }
}
