// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class SLODefinitionBurnRateAlertingConfig
    {
        public readonly double Budget;
        public readonly ImmutableDictionary<string, string>? Labels;
        public readonly string Severity;
        public readonly string Window;

        [OutputConstructor]
        private SLODefinitionBurnRateAlertingConfig(
            double budget,

            ImmutableDictionary<string, string>? labels,

            string severity,

            string window)
        {
            Budget = budget;
            Labels = labels;
            Severity = severity;
            Window = window;
        }
    }
}
