// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Outputs
{

    [OutputType]
    public sealed class TraceMetricsRuleTraceFilterSpanDuration
    {
        /// <summary>
        /// Maximum duration in seconds, inclusive. Omit for no upper bound.
        /// </summary>
        public readonly double? MaxSecs;
        /// <summary>
        /// Minimum duration in seconds, inclusive. Defaults to `0`.
        /// </summary>
        public readonly double? MinSecs;

        [OutputConstructor]
        private TraceMetricsRuleTraceFilterSpanDuration(
            double? maxSecs,

            double? minSecs)
        {
            MaxSecs = maxSecs;
            MinSecs = minSecs;
        }
    }
}
