// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BlackholeAlertNotifierState extends com.pulumi.resources.ResourceArgs {

    public static final BlackholeAlertNotifierState Empty = new BlackholeAlertNotifierState();

    /**
     * Display name of the notifier.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Display name of the notifier.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Stable identifier for the notifier. Generated from `name` if omitted. Immutable after creation.
     * 
     */
    @Import(name="slug")
    private @Nullable Output<String> slug;

    /**
     * @return Stable identifier for the notifier. Generated from `name` if omitted. Immutable after creation.
     * 
     */
    public Optional<Output<String>> slug() {
        return Optional.ofNullable(this.slug);
    }

    private BlackholeAlertNotifierState() {}

    private BlackholeAlertNotifierState(BlackholeAlertNotifierState $) {
        this.name = $.name;
        this.slug = $.slug;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BlackholeAlertNotifierState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BlackholeAlertNotifierState $;

        public Builder() {
            $ = new BlackholeAlertNotifierState();
        }

        public Builder(BlackholeAlertNotifierState defaults) {
            $ = new BlackholeAlertNotifierState(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Display name of the notifier.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Display name of the notifier.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param slug Stable identifier for the notifier. Generated from `name` if omitted. Immutable after creation.
         * 
         * @return builder
         * 
         */
        public Builder slug(@Nullable Output<String> slug) {
            $.slug = slug;
            return this;
        }

        /**
         * @param slug Stable identifier for the notifier. Generated from `name` if omitted. Immutable after creation.
         * 
         * @return builder
         * 
         */
        public Builder slug(String slug) {
            return slug(Output.of(slug));
        }

        public BlackholeAlertNotifierState build() {
            return $;
        }
    }

}
