// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.chronosphere.chronosphere.inputs.ConsumptionConfigPartitionPartitionFilterArgs;
import io.chronosphere.chronosphere.inputs.ConsumptionConfigPartitionPartitionPartitionArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConsumptionConfigPartitionPartitionArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConsumptionConfigPartitionPartitionArgs Empty = new ConsumptionConfigPartitionPartitionArgs();

    /**
     * Filters identifying which data belongs to this partition. Filters are AND-ed together: a request must match every filter to be assigned to the partition. At most one `IN` filter and one `NOT_IN` filter can be specified.
     * 
     */
    @Import(name="filters")
    private @Nullable Output<List<ConsumptionConfigPartitionPartitionFilterArgs>> filters;

    /**
     * @return Filters identifying which data belongs to this partition. Filters are AND-ed together: a request must match every filter to be assigned to the partition. At most one `IN` filter and one `NOT_IN` filter can be specified.
     * 
     */
    public Optional<Output<List<ConsumptionConfigPartitionPartitionFilterArgs>>> filters() {
        return Optional.ofNullable(this.filters);
    }

    /**
     * Display name of the partition. Must be unique within its parent partition. Can be changed after creation.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Display name of the partition. Must be unique within its parent partition. Can be changed after creation.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Child partitions of this partition. Evaluated in order; requests not matching any child fall into an implicit `default` child partition.
     * 
     */
    @Import(name="partitions")
    private @Nullable Output<List<ConsumptionConfigPartitionPartitionPartitionArgs>> partitions;

    /**
     * @return Child partitions of this partition. Evaluated in order; requests not matching any child fall into an implicit `default` child partition.
     * 
     */
    public Optional<Output<List<ConsumptionConfigPartitionPartitionPartitionArgs>>> partitions() {
        return Optional.ofNullable(this.partitions);
    }

    /**
     * Stable identifier of the partition. Must be unique within its parent partition. Immutable after creation.
     * 
     */
    @Import(name="slug")
    private @Nullable Output<String> slug;

    /**
     * @return Stable identifier of the partition. Must be unique within its parent partition. Immutable after creation.
     * 
     */
    public Optional<Output<String>> slug() {
        return Optional.ofNullable(this.slug);
    }

    private ConsumptionConfigPartitionPartitionArgs() {}

    private ConsumptionConfigPartitionPartitionArgs(ConsumptionConfigPartitionPartitionArgs $) {
        this.filters = $.filters;
        this.name = $.name;
        this.partitions = $.partitions;
        this.slug = $.slug;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConsumptionConfigPartitionPartitionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConsumptionConfigPartitionPartitionArgs $;

        public Builder() {
            $ = new ConsumptionConfigPartitionPartitionArgs();
        }

        public Builder(ConsumptionConfigPartitionPartitionArgs defaults) {
            $ = new ConsumptionConfigPartitionPartitionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param filters Filters identifying which data belongs to this partition. Filters are AND-ed together: a request must match every filter to be assigned to the partition. At most one `IN` filter and one `NOT_IN` filter can be specified.
         * 
         * @return builder
         * 
         */
        public Builder filters(@Nullable Output<List<ConsumptionConfigPartitionPartitionFilterArgs>> filters) {
            $.filters = filters;
            return this;
        }

        /**
         * @param filters Filters identifying which data belongs to this partition. Filters are AND-ed together: a request must match every filter to be assigned to the partition. At most one `IN` filter and one `NOT_IN` filter can be specified.
         * 
         * @return builder
         * 
         */
        public Builder filters(List<ConsumptionConfigPartitionPartitionFilterArgs> filters) {
            return filters(Output.of(filters));
        }

        /**
         * @param filters Filters identifying which data belongs to this partition. Filters are AND-ed together: a request must match every filter to be assigned to the partition. At most one `IN` filter and one `NOT_IN` filter can be specified.
         * 
         * @return builder
         * 
         */
        public Builder filters(ConsumptionConfigPartitionPartitionFilterArgs... filters) {
            return filters(List.of(filters));
        }

        /**
         * @param name Display name of the partition. Must be unique within its parent partition. Can be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Display name of the partition. Must be unique within its parent partition. Can be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param partitions Child partitions of this partition. Evaluated in order; requests not matching any child fall into an implicit `default` child partition.
         * 
         * @return builder
         * 
         */
        public Builder partitions(@Nullable Output<List<ConsumptionConfigPartitionPartitionPartitionArgs>> partitions) {
            $.partitions = partitions;
            return this;
        }

        /**
         * @param partitions Child partitions of this partition. Evaluated in order; requests not matching any child fall into an implicit `default` child partition.
         * 
         * @return builder
         * 
         */
        public Builder partitions(List<ConsumptionConfigPartitionPartitionPartitionArgs> partitions) {
            return partitions(Output.of(partitions));
        }

        /**
         * @param partitions Child partitions of this partition. Evaluated in order; requests not matching any child fall into an implicit `default` child partition.
         * 
         * @return builder
         * 
         */
        public Builder partitions(ConsumptionConfigPartitionPartitionPartitionArgs... partitions) {
            return partitions(List.of(partitions));
        }

        /**
         * @param slug Stable identifier of the partition. Must be unique within its parent partition. Immutable after creation.
         * 
         * @return builder
         * 
         */
        public Builder slug(@Nullable Output<String> slug) {
            $.slug = slug;
            return this;
        }

        /**
         * @param slug Stable identifier of the partition. Must be unique within its parent partition. Immutable after creation.
         * 
         * @return builder
         * 
         */
        public Builder slug(String slug) {
            return slug(Output.of(slug));
        }

        public ConsumptionConfigPartitionPartitionArgs build() {
            return $;
        }
    }

}
