// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.chronosphere.chronosphere.inputs.ConsumptionBudgetAlertActionConfigArgs;
import io.chronosphere.chronosphere.inputs.ConsumptionBudgetPriorityArgs;
import io.chronosphere.chronosphere.inputs.ConsumptionBudgetThresholdArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConsumptionBudgetState extends com.pulumi.resources.ResourceArgs {

    public static final ConsumptionBudgetState Empty = new ConsumptionBudgetState();

    /**
     * Optional configuration applied to monitors generated by alerting thresholds.
     * 
     */
    @Import(name="alertActionConfig")
    private @Nullable Output<ConsumptionBudgetAlertActionConfigArgs> alertActionConfig;

    /**
     * @return Optional configuration applied to monitors generated by alerting thresholds.
     * 
     */
    public Optional<Output<ConsumptionBudgetAlertActionConfigArgs>> alertActionConfig() {
        return Optional.ofNullable(this.alertActionConfig);
    }

    /**
     * ID of the singleton `chronosphere.ConsumptionConfig` resource this budget depends on. Acts as an explicit dependency pointer; the actual partition is selected via `partitionSlugPath`.
     * 
     */
    @Import(name="consumptionConfigId")
    private @Nullable Output<String> consumptionConfigId;

    /**
     * @return ID of the singleton `chronosphere.ConsumptionConfig` resource this budget depends on. Acts as an explicit dependency pointer; the actual partition is selected via `partitionSlugPath`.
     * 
     */
    public Optional<Output<String>> consumptionConfigId() {
        return Optional.ofNullable(this.consumptionConfigId);
    }

    /**
     * Priority assigned to requests that do not match any entry in `priority`. Defaults to 10 (dropped first) if unset.
     * 
     */
    @Import(name="defaultPriority")
    private @Nullable Output<Integer> defaultPriority;

    /**
     * @return Priority assigned to requests that do not match any entry in `priority`. Defaults to 10 (dropped first) if unset.
     * 
     */
    public Optional<Output<Integer>> defaultPriority() {
        return Optional.ofNullable(this.defaultPriority);
    }

    /**
     * Display name of the consumption budget. Can be changed after creation.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Display name of the consumption budget. Can be changed after creation.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * ID of the notification policy used to route alerts generated by `ALERT_WARN`/`ALERT_CRITICAL` thresholds. Required only if such thresholds are configured.
     * 
     */
    @Import(name="notificationPolicyId")
    private @Nullable Output<String> notificationPolicyId;

    /**
     * @return ID of the notification policy used to route alerts generated by `ALERT_WARN`/`ALERT_CRITICAL` thresholds. Required only if such thresholds are configured.
     * 
     */
    public Optional<Output<String>> notificationPolicyId() {
        return Optional.ofNullable(this.notificationPolicyId);
    }

    /**
     * Forward-slash-delimited path identifying the partition the budget applies to (e.g. `global/gateway/dev`). Must start with the `global` partition slug.
     * 
     */
    @Import(name="partitionSlugPath")
    private @Nullable Output<String> partitionSlugPath;

    /**
     * @return Forward-slash-delimited path identifying the partition the budget applies to (e.g. `global/gateway/dev`). Must start with the `global` partition slug.
     * 
     */
    public Optional<Output<String>> partitionSlugPath() {
        return Optional.ofNullable(this.partitionSlugPath);
    }

    /**
     * Ordered list of priority rules that classify incoming data. When a drop action runs, higher-numbered priorities (e.g. 10) are dropped first and priority 1 is dropped last. Evaluation stops at the first matching priority.
     * 
     */
    @Import(name="priorities")
    private @Nullable Output<List<ConsumptionBudgetPriorityArgs>> priorities;

    /**
     * @return Ordered list of priority rules that classify incoming data. When a drop action runs, higher-numbered priorities (e.g. 10) are dropped first and priority 1 is dropped last. Evaluation stops at the first matching priority.
     * 
     */
    public Optional<Output<List<ConsumptionBudgetPriorityArgs>>> priorities() {
        return Optional.ofNullable(this.priorities);
    }

    /**
     * Deprecated: use `threshold.resource_group` and `threshold.unit` instead. Identifies the resource type the budget governs.
     * 
     * @deprecated
     * use threshold.resource_group and threshold.unit instead
     * 
     */
    @Deprecated /* use threshold.resource_group and threshold.unit instead */
    @Import(name="resource")
    private @Nullable Output<String> resource;

    /**
     * @return Deprecated: use `threshold.resource_group` and `threshold.unit` instead. Identifies the resource type the budget governs.
     * 
     * @deprecated
     * use threshold.resource_group and threshold.unit instead
     * 
     */
    @Deprecated /* use threshold.resource_group and threshold.unit instead */
    public Optional<Output<String>> resource() {
        return Optional.ofNullable(this.resource);
    }

    /**
     * Stable identifier for the consumption budget. Generated from `name` if omitted. Immutable after creation.
     * 
     */
    @Import(name="slug")
    private @Nullable Output<String> slug;

    /**
     * @return Stable identifier for the consumption budget. Generated from `name` if omitted. Immutable after creation.
     * 
     */
    public Optional<Output<String>> slug() {
        return Optional.ofNullable(this.slug);
    }

    /**
     * Threshold actions to take when budget consumption crosses configured levels.
     * 
     */
    @Import(name="thresholds")
    private @Nullable Output<List<ConsumptionBudgetThresholdArgs>> thresholds;

    /**
     * @return Threshold actions to take when budget consumption crosses configured levels.
     * 
     */
    public Optional<Output<List<ConsumptionBudgetThresholdArgs>>> thresholds() {
        return Optional.ofNullable(this.thresholds);
    }

    private ConsumptionBudgetState() {}

    private ConsumptionBudgetState(ConsumptionBudgetState $) {
        this.alertActionConfig = $.alertActionConfig;
        this.consumptionConfigId = $.consumptionConfigId;
        this.defaultPriority = $.defaultPriority;
        this.name = $.name;
        this.notificationPolicyId = $.notificationPolicyId;
        this.partitionSlugPath = $.partitionSlugPath;
        this.priorities = $.priorities;
        this.resource = $.resource;
        this.slug = $.slug;
        this.thresholds = $.thresholds;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConsumptionBudgetState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConsumptionBudgetState $;

        public Builder() {
            $ = new ConsumptionBudgetState();
        }

        public Builder(ConsumptionBudgetState defaults) {
            $ = new ConsumptionBudgetState(Objects.requireNonNull(defaults));
        }

        /**
         * @param alertActionConfig Optional configuration applied to monitors generated by alerting thresholds.
         * 
         * @return builder
         * 
         */
        public Builder alertActionConfig(@Nullable Output<ConsumptionBudgetAlertActionConfigArgs> alertActionConfig) {
            $.alertActionConfig = alertActionConfig;
            return this;
        }

        /**
         * @param alertActionConfig Optional configuration applied to monitors generated by alerting thresholds.
         * 
         * @return builder
         * 
         */
        public Builder alertActionConfig(ConsumptionBudgetAlertActionConfigArgs alertActionConfig) {
            return alertActionConfig(Output.of(alertActionConfig));
        }

        /**
         * @param consumptionConfigId ID of the singleton `chronosphere.ConsumptionConfig` resource this budget depends on. Acts as an explicit dependency pointer; the actual partition is selected via `partitionSlugPath`.
         * 
         * @return builder
         * 
         */
        public Builder consumptionConfigId(@Nullable Output<String> consumptionConfigId) {
            $.consumptionConfigId = consumptionConfigId;
            return this;
        }

        /**
         * @param consumptionConfigId ID of the singleton `chronosphere.ConsumptionConfig` resource this budget depends on. Acts as an explicit dependency pointer; the actual partition is selected via `partitionSlugPath`.
         * 
         * @return builder
         * 
         */
        public Builder consumptionConfigId(String consumptionConfigId) {
            return consumptionConfigId(Output.of(consumptionConfigId));
        }

        /**
         * @param defaultPriority Priority assigned to requests that do not match any entry in `priority`. Defaults to 10 (dropped first) if unset.
         * 
         * @return builder
         * 
         */
        public Builder defaultPriority(@Nullable Output<Integer> defaultPriority) {
            $.defaultPriority = defaultPriority;
            return this;
        }

        /**
         * @param defaultPriority Priority assigned to requests that do not match any entry in `priority`. Defaults to 10 (dropped first) if unset.
         * 
         * @return builder
         * 
         */
        public Builder defaultPriority(Integer defaultPriority) {
            return defaultPriority(Output.of(defaultPriority));
        }

        /**
         * @param name Display name of the consumption budget. Can be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Display name of the consumption budget. Can be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param notificationPolicyId ID of the notification policy used to route alerts generated by `ALERT_WARN`/`ALERT_CRITICAL` thresholds. Required only if such thresholds are configured.
         * 
         * @return builder
         * 
         */
        public Builder notificationPolicyId(@Nullable Output<String> notificationPolicyId) {
            $.notificationPolicyId = notificationPolicyId;
            return this;
        }

        /**
         * @param notificationPolicyId ID of the notification policy used to route alerts generated by `ALERT_WARN`/`ALERT_CRITICAL` thresholds. Required only if such thresholds are configured.
         * 
         * @return builder
         * 
         */
        public Builder notificationPolicyId(String notificationPolicyId) {
            return notificationPolicyId(Output.of(notificationPolicyId));
        }

        /**
         * @param partitionSlugPath Forward-slash-delimited path identifying the partition the budget applies to (e.g. `global/gateway/dev`). Must start with the `global` partition slug.
         * 
         * @return builder
         * 
         */
        public Builder partitionSlugPath(@Nullable Output<String> partitionSlugPath) {
            $.partitionSlugPath = partitionSlugPath;
            return this;
        }

        /**
         * @param partitionSlugPath Forward-slash-delimited path identifying the partition the budget applies to (e.g. `global/gateway/dev`). Must start with the `global` partition slug.
         * 
         * @return builder
         * 
         */
        public Builder partitionSlugPath(String partitionSlugPath) {
            return partitionSlugPath(Output.of(partitionSlugPath));
        }

        /**
         * @param priorities Ordered list of priority rules that classify incoming data. When a drop action runs, higher-numbered priorities (e.g. 10) are dropped first and priority 1 is dropped last. Evaluation stops at the first matching priority.
         * 
         * @return builder
         * 
         */
        public Builder priorities(@Nullable Output<List<ConsumptionBudgetPriorityArgs>> priorities) {
            $.priorities = priorities;
            return this;
        }

        /**
         * @param priorities Ordered list of priority rules that classify incoming data. When a drop action runs, higher-numbered priorities (e.g. 10) are dropped first and priority 1 is dropped last. Evaluation stops at the first matching priority.
         * 
         * @return builder
         * 
         */
        public Builder priorities(List<ConsumptionBudgetPriorityArgs> priorities) {
            return priorities(Output.of(priorities));
        }

        /**
         * @param priorities Ordered list of priority rules that classify incoming data. When a drop action runs, higher-numbered priorities (e.g. 10) are dropped first and priority 1 is dropped last. Evaluation stops at the first matching priority.
         * 
         * @return builder
         * 
         */
        public Builder priorities(ConsumptionBudgetPriorityArgs... priorities) {
            return priorities(List.of(priorities));
        }

        /**
         * @param resource Deprecated: use `threshold.resource_group` and `threshold.unit` instead. Identifies the resource type the budget governs.
         * 
         * @return builder
         * 
         * @deprecated
         * use threshold.resource_group and threshold.unit instead
         * 
         */
        @Deprecated /* use threshold.resource_group and threshold.unit instead */
        public Builder resource(@Nullable Output<String> resource) {
            $.resource = resource;
            return this;
        }

        /**
         * @param resource Deprecated: use `threshold.resource_group` and `threshold.unit` instead. Identifies the resource type the budget governs.
         * 
         * @return builder
         * 
         * @deprecated
         * use threshold.resource_group and threshold.unit instead
         * 
         */
        @Deprecated /* use threshold.resource_group and threshold.unit instead */
        public Builder resource(String resource) {
            return resource(Output.of(resource));
        }

        /**
         * @param slug Stable identifier for the consumption budget. Generated from `name` if omitted. Immutable after creation.
         * 
         * @return builder
         * 
         */
        public Builder slug(@Nullable Output<String> slug) {
            $.slug = slug;
            return this;
        }

        /**
         * @param slug Stable identifier for the consumption budget. Generated from `name` if omitted. Immutable after creation.
         * 
         * @return builder
         * 
         */
        public Builder slug(String slug) {
            return slug(Output.of(slug));
        }

        /**
         * @param thresholds Threshold actions to take when budget consumption crosses configured levels.
         * 
         * @return builder
         * 
         */
        public Builder thresholds(@Nullable Output<List<ConsumptionBudgetThresholdArgs>> thresholds) {
            $.thresholds = thresholds;
            return this;
        }

        /**
         * @param thresholds Threshold actions to take when budget consumption crosses configured levels.
         * 
         * @return builder
         * 
         */
        public Builder thresholds(List<ConsumptionBudgetThresholdArgs> thresholds) {
            return thresholds(Output.of(thresholds));
        }

        /**
         * @param thresholds Threshold actions to take when budget consumption crosses configured levels.
         * 
         * @return builder
         * 
         */
        public Builder thresholds(ConsumptionBudgetThresholdArgs... thresholds) {
            return thresholds(List.of(thresholds));
        }

        public ConsumptionBudgetState build() {
            return $;
        }
    }

}
