// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.chronosphere.chronosphere.inputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterDurationArgs;
import io.chronosphere.chronosphere.inputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterErrorArgs;
import io.chronosphere.chronosphere.inputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterIsRootSpanArgs;
import io.chronosphere.chronosphere.inputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterOperationArgs;
import io.chronosphere.chronosphere.inputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentOperationArgs;
import io.chronosphere.chronosphere.inputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentServiceArgs;
import io.chronosphere.chronosphere.inputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterServiceArgs;
import io.chronosphere.chronosphere.inputs.ConsumptionConfigPartitionFilterConditionTraceSpanFilterTagArgs;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConsumptionConfigPartitionFilterConditionTraceSpanFilterArgs extends com.pulumi.resources.ResourceArgs {

    public static final ConsumptionConfigPartitionFilterConditionTraceSpanFilterArgs Empty = new ConsumptionConfigPartitionFilterConditionTraceSpanFilterArgs();

    /**
     * Matches traces or spans whose duration in seconds falls within the inclusive `[min_secs, maxSecs]` range.
     * 
     */
    @Import(name="duration")
    private @Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterDurationArgs> duration;

    /**
     * @return Matches traces or spans whose duration in seconds falls within the inclusive `[min_secs, maxSecs]` range.
     * 
     */
    public Optional<Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterDurationArgs>> duration() {
        return Optional.ofNullable(this.duration);
    }

    /**
     * Matches traces or spans where the target boolean field equals `value`.
     * 
     */
    @Import(name="error")
    private @Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterErrorArgs> error;

    /**
     * @return Matches traces or spans where the target boolean field equals `value`.
     * 
     */
    public Optional<Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterErrorArgs>> error() {
        return Optional.ofNullable(this.error);
    }

    /**
     * Matches traces or spans where the target boolean field equals `value`.
     * 
     */
    @Import(name="isRootSpan")
    private @Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterIsRootSpanArgs> isRootSpan;

    /**
     * @return Matches traces or spans where the target boolean field equals `value`.
     * 
     */
    public Optional<Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterIsRootSpanArgs>> isRootSpan() {
        return Optional.ofNullable(this.isRootSpan);
    }

    /**
     * Matches traces or spans where the target string field satisfies the match condition.
     * 
     */
    @Import(name="operation")
    private @Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterOperationArgs> operation;

    /**
     * @return Matches traces or spans where the target string field satisfies the match condition.
     * 
     */
    public Optional<Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterOperationArgs>> operation() {
        return Optional.ofNullable(this.operation);
    }

    /**
     * Matches traces or spans where the target string field satisfies the match condition.
     * 
     */
    @Import(name="parentOperation")
    private @Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentOperationArgs> parentOperation;

    /**
     * @return Matches traces or spans where the target string field satisfies the match condition.
     * 
     */
    public Optional<Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentOperationArgs>> parentOperation() {
        return Optional.ofNullable(this.parentOperation);
    }

    /**
     * Matches traces or spans where the target string field satisfies the match condition.
     * 
     */
    @Import(name="parentService")
    private @Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentServiceArgs> parentService;

    /**
     * @return Matches traces or spans where the target string field satisfies the match condition.
     * 
     */
    public Optional<Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentServiceArgs>> parentService() {
        return Optional.ofNullable(this.parentService);
    }

    /**
     * Matches traces or spans where the target string field satisfies the match condition.
     * 
     */
    @Import(name="service")
    private @Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterServiceArgs> service;

    /**
     * @return Matches traces or spans where the target string field satisfies the match condition.
     * 
     */
    public Optional<Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterServiceArgs>> service() {
        return Optional.ofNullable(this.service);
    }

    /**
     * Matches spans whose tag (span attribute) with the given `key` has a value satisfying the nested string or numeric filter.
     * 
     */
    @Import(name="tags")
    private @Nullable Output<List<ConsumptionConfigPartitionFilterConditionTraceSpanFilterTagArgs>> tags;

    /**
     * @return Matches spans whose tag (span attribute) with the given `key` has a value satisfying the nested string or numeric filter.
     * 
     */
    public Optional<Output<List<ConsumptionConfigPartitionFilterConditionTraceSpanFilterTagArgs>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    private ConsumptionConfigPartitionFilterConditionTraceSpanFilterArgs() {}

    private ConsumptionConfigPartitionFilterConditionTraceSpanFilterArgs(ConsumptionConfigPartitionFilterConditionTraceSpanFilterArgs $) {
        this.duration = $.duration;
        this.error = $.error;
        this.isRootSpan = $.isRootSpan;
        this.operation = $.operation;
        this.parentOperation = $.parentOperation;
        this.parentService = $.parentService;
        this.service = $.service;
        this.tags = $.tags;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConsumptionConfigPartitionFilterConditionTraceSpanFilterArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConsumptionConfigPartitionFilterConditionTraceSpanFilterArgs $;

        public Builder() {
            $ = new ConsumptionConfigPartitionFilterConditionTraceSpanFilterArgs();
        }

        public Builder(ConsumptionConfigPartitionFilterConditionTraceSpanFilterArgs defaults) {
            $ = new ConsumptionConfigPartitionFilterConditionTraceSpanFilterArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param duration Matches traces or spans whose duration in seconds falls within the inclusive `[min_secs, maxSecs]` range.
         * 
         * @return builder
         * 
         */
        public Builder duration(@Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterDurationArgs> duration) {
            $.duration = duration;
            return this;
        }

        /**
         * @param duration Matches traces or spans whose duration in seconds falls within the inclusive `[min_secs, maxSecs]` range.
         * 
         * @return builder
         * 
         */
        public Builder duration(ConsumptionConfigPartitionFilterConditionTraceSpanFilterDurationArgs duration) {
            return duration(Output.of(duration));
        }

        /**
         * @param error Matches traces or spans where the target boolean field equals `value`.
         * 
         * @return builder
         * 
         */
        public Builder error(@Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterErrorArgs> error) {
            $.error = error;
            return this;
        }

        /**
         * @param error Matches traces or spans where the target boolean field equals `value`.
         * 
         * @return builder
         * 
         */
        public Builder error(ConsumptionConfigPartitionFilterConditionTraceSpanFilterErrorArgs error) {
            return error(Output.of(error));
        }

        /**
         * @param isRootSpan Matches traces or spans where the target boolean field equals `value`.
         * 
         * @return builder
         * 
         */
        public Builder isRootSpan(@Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterIsRootSpanArgs> isRootSpan) {
            $.isRootSpan = isRootSpan;
            return this;
        }

        /**
         * @param isRootSpan Matches traces or spans where the target boolean field equals `value`.
         * 
         * @return builder
         * 
         */
        public Builder isRootSpan(ConsumptionConfigPartitionFilterConditionTraceSpanFilterIsRootSpanArgs isRootSpan) {
            return isRootSpan(Output.of(isRootSpan));
        }

        /**
         * @param operation Matches traces or spans where the target string field satisfies the match condition.
         * 
         * @return builder
         * 
         */
        public Builder operation(@Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterOperationArgs> operation) {
            $.operation = operation;
            return this;
        }

        /**
         * @param operation Matches traces or spans where the target string field satisfies the match condition.
         * 
         * @return builder
         * 
         */
        public Builder operation(ConsumptionConfigPartitionFilterConditionTraceSpanFilterOperationArgs operation) {
            return operation(Output.of(operation));
        }

        /**
         * @param parentOperation Matches traces or spans where the target string field satisfies the match condition.
         * 
         * @return builder
         * 
         */
        public Builder parentOperation(@Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentOperationArgs> parentOperation) {
            $.parentOperation = parentOperation;
            return this;
        }

        /**
         * @param parentOperation Matches traces or spans where the target string field satisfies the match condition.
         * 
         * @return builder
         * 
         */
        public Builder parentOperation(ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentOperationArgs parentOperation) {
            return parentOperation(Output.of(parentOperation));
        }

        /**
         * @param parentService Matches traces or spans where the target string field satisfies the match condition.
         * 
         * @return builder
         * 
         */
        public Builder parentService(@Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentServiceArgs> parentService) {
            $.parentService = parentService;
            return this;
        }

        /**
         * @param parentService Matches traces or spans where the target string field satisfies the match condition.
         * 
         * @return builder
         * 
         */
        public Builder parentService(ConsumptionConfigPartitionFilterConditionTraceSpanFilterParentServiceArgs parentService) {
            return parentService(Output.of(parentService));
        }

        /**
         * @param service Matches traces or spans where the target string field satisfies the match condition.
         * 
         * @return builder
         * 
         */
        public Builder service(@Nullable Output<ConsumptionConfigPartitionFilterConditionTraceSpanFilterServiceArgs> service) {
            $.service = service;
            return this;
        }

        /**
         * @param service Matches traces or spans where the target string field satisfies the match condition.
         * 
         * @return builder
         * 
         */
        public Builder service(ConsumptionConfigPartitionFilterConditionTraceSpanFilterServiceArgs service) {
            return service(Output.of(service));
        }

        /**
         * @param tags Matches spans whose tag (span attribute) with the given `key` has a value satisfying the nested string or numeric filter.
         * 
         * @return builder
         * 
         */
        public Builder tags(@Nullable Output<List<ConsumptionConfigPartitionFilterConditionTraceSpanFilterTagArgs>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags Matches spans whose tag (span attribute) with the given `key` has a value satisfying the nested string or numeric filter.
         * 
         * @return builder
         * 
         */
        public Builder tags(List<ConsumptionConfigPartitionFilterConditionTraceSpanFilterTagArgs> tags) {
            return tags(Output.of(tags));
        }

        /**
         * @param tags Matches spans whose tag (span attribute) with the given `key` has a value satisfying the nested string or numeric filter.
         * 
         * @return builder
         * 
         */
        public Builder tags(ConsumptionConfigPartitionFilterConditionTraceSpanFilterTagArgs... tags) {
            return tags(List.of(tags));
        }

        public ConsumptionConfigPartitionFilterConditionTraceSpanFilterArgs build() {
            return $;
        }
    }

}
