// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.chronosphere.chronosphere.inputs.DatasetConfigurationTraceDatasetMatchCriteriaArgs;
import java.util.Objects;


public final class DatasetConfigurationTraceDatasetArgs extends com.pulumi.resources.ResourceArgs {

    public static final DatasetConfigurationTraceDatasetArgs Empty = new DatasetConfigurationTraceDatasetArgs();

    @Import(name="matchCriteria", required=true)
    private Output<DatasetConfigurationTraceDatasetMatchCriteriaArgs> matchCriteria;

    public Output<DatasetConfigurationTraceDatasetMatchCriteriaArgs> matchCriteria() {
        return this.matchCriteria;
    }

    private DatasetConfigurationTraceDatasetArgs() {}

    private DatasetConfigurationTraceDatasetArgs(DatasetConfigurationTraceDatasetArgs $) {
        this.matchCriteria = $.matchCriteria;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DatasetConfigurationTraceDatasetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DatasetConfigurationTraceDatasetArgs $;

        public Builder() {
            $ = new DatasetConfigurationTraceDatasetArgs();
        }

        public Builder(DatasetConfigurationTraceDatasetArgs defaults) {
            $ = new DatasetConfigurationTraceDatasetArgs(Objects.requireNonNull(defaults));
        }

        public Builder matchCriteria(Output<DatasetConfigurationTraceDatasetMatchCriteriaArgs> matchCriteria) {
            $.matchCriteria = matchCriteria;
            return this;
        }

        public Builder matchCriteria(DatasetConfigurationTraceDatasetMatchCriteriaArgs matchCriteria) {
            return matchCriteria(Output.of(matchCriteria));
        }

        public DatasetConfigurationTraceDatasetArgs build() {
            $.matchCriteria = Objects.requireNonNull($.matchCriteria, "expected parameter 'matchCriteria' to be non-null");
            return $;
        }
    }

}
