// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DatasetConfigurationTraceDatasetMatchCriteriaSpanSpanCountArgs extends com.pulumi.resources.ResourceArgs {

    public static final DatasetConfigurationTraceDatasetMatchCriteriaSpanSpanCountArgs Empty = new DatasetConfigurationTraceDatasetMatchCriteriaSpanSpanCountArgs();

    /**
     * Maximum number of matching spans, inclusive. `0` means no upper bound.
     * 
     */
    @Import(name="max")
    private @Nullable Output<Integer> max;

    /**
     * @return Maximum number of matching spans, inclusive. `0` means no upper bound.
     * 
     */
    public Optional<Output<Integer>> max() {
        return Optional.ofNullable(this.max);
    }

    /**
     * Minimum number of matching spans, inclusive. Defaults to `0`.
     * 
     */
    @Import(name="min")
    private @Nullable Output<Integer> min;

    /**
     * @return Minimum number of matching spans, inclusive. Defaults to `0`.
     * 
     */
    public Optional<Output<Integer>> min() {
        return Optional.ofNullable(this.min);
    }

    private DatasetConfigurationTraceDatasetMatchCriteriaSpanSpanCountArgs() {}

    private DatasetConfigurationTraceDatasetMatchCriteriaSpanSpanCountArgs(DatasetConfigurationTraceDatasetMatchCriteriaSpanSpanCountArgs $) {
        this.max = $.max;
        this.min = $.min;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DatasetConfigurationTraceDatasetMatchCriteriaSpanSpanCountArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DatasetConfigurationTraceDatasetMatchCriteriaSpanSpanCountArgs $;

        public Builder() {
            $ = new DatasetConfigurationTraceDatasetMatchCriteriaSpanSpanCountArgs();
        }

        public Builder(DatasetConfigurationTraceDatasetMatchCriteriaSpanSpanCountArgs defaults) {
            $ = new DatasetConfigurationTraceDatasetMatchCriteriaSpanSpanCountArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param max Maximum number of matching spans, inclusive. `0` means no upper bound.
         * 
         * @return builder
         * 
         */
        public Builder max(@Nullable Output<Integer> max) {
            $.max = max;
            return this;
        }

        /**
         * @param max Maximum number of matching spans, inclusive. `0` means no upper bound.
         * 
         * @return builder
         * 
         */
        public Builder max(Integer max) {
            return max(Output.of(max));
        }

        /**
         * @param min Minimum number of matching spans, inclusive. Defaults to `0`.
         * 
         * @return builder
         * 
         */
        public Builder min(@Nullable Output<Integer> min) {
            $.min = min;
            return this;
        }

        /**
         * @param min Minimum number of matching spans, inclusive. Defaults to `0`.
         * 
         * @return builder
         * 
         */
        public Builder min(Integer min) {
            return min(Output.of(min));
        }

        public DatasetConfigurationTraceDatasetMatchCriteriaSpanSpanCountArgs build() {
            return $;
        }
    }

}
