// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.chronosphere.chronosphere.inputs.DatasetConfigurationArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DatasetState extends com.pulumi.resources.ResourceArgs {

    public static final DatasetState Empty = new DatasetState();

    /**
     * Configuration block selecting the dataset type and its match criteria.
     * 
     */
    @Import(name="configuration")
    private @Nullable Output<DatasetConfigurationArgs> configuration;

    /**
     * @return Configuration block selecting the dataset type and its match criteria.
     * 
     */
    public Optional<Output<DatasetConfigurationArgs>> configuration() {
        return Optional.ofNullable(this.configuration);
    }

    /**
     * Free-form description of the dataset.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Free-form description of the dataset.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * Display name of the dataset. Can be changed after creation.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Display name of the dataset. Can be changed after creation.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Stable identifier for the dataset. Generated from `name` if omitted. Immutable after creation.
     * 
     */
    @Import(name="slug")
    private @Nullable Output<String> slug;

    /**
     * @return Stable identifier for the dataset. Generated from `name` if omitted. Immutable after creation.
     * 
     */
    public Optional<Output<String>> slug() {
        return Optional.ofNullable(this.slug);
    }

    private DatasetState() {}

    private DatasetState(DatasetState $) {
        this.configuration = $.configuration;
        this.description = $.description;
        this.name = $.name;
        this.slug = $.slug;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DatasetState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DatasetState $;

        public Builder() {
            $ = new DatasetState();
        }

        public Builder(DatasetState defaults) {
            $ = new DatasetState(Objects.requireNonNull(defaults));
        }

        /**
         * @param configuration Configuration block selecting the dataset type and its match criteria.
         * 
         * @return builder
         * 
         */
        public Builder configuration(@Nullable Output<DatasetConfigurationArgs> configuration) {
            $.configuration = configuration;
            return this;
        }

        /**
         * @param configuration Configuration block selecting the dataset type and its match criteria.
         * 
         * @return builder
         * 
         */
        public Builder configuration(DatasetConfigurationArgs configuration) {
            return configuration(Output.of(configuration));
        }

        /**
         * @param description Free-form description of the dataset.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Free-form description of the dataset.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param name Display name of the dataset. Can be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Display name of the dataset. Can be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param slug Stable identifier for the dataset. Generated from `name` if omitted. Immutable after creation.
         * 
         * @return builder
         * 
         */
        public Builder slug(@Nullable Output<String> slug) {
            $.slug = slug;
            return this;
        }

        /**
         * @param slug Stable identifier for the dataset. Generated from `name` if omitted. Immutable after creation.
         * 
         * @return builder
         * 
         */
        public Builder slug(String slug) {
            return slug(Output.of(slug));
        }

        public DatasetState build() {
            return $;
        }
    }

}
