// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.chronosphere.chronosphere.inputs.DerivedLabelMetricLabelConstructedLabelValueDefinitionArgs;
import java.util.List;
import java.util.Objects;


public final class DerivedLabelMetricLabelConstructedLabelArgs extends com.pulumi.resources.ResourceArgs {

    public static final DerivedLabelMetricLabelConstructedLabelArgs Empty = new DerivedLabelMetricLabelConstructedLabelArgs();

    @Import(name="valueDefinitions", required=true)
    private Output<List<DerivedLabelMetricLabelConstructedLabelValueDefinitionArgs>> valueDefinitions;

    public Output<List<DerivedLabelMetricLabelConstructedLabelValueDefinitionArgs>> valueDefinitions() {
        return this.valueDefinitions;
    }

    private DerivedLabelMetricLabelConstructedLabelArgs() {}

    private DerivedLabelMetricLabelConstructedLabelArgs(DerivedLabelMetricLabelConstructedLabelArgs $) {
        this.valueDefinitions = $.valueDefinitions;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DerivedLabelMetricLabelConstructedLabelArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DerivedLabelMetricLabelConstructedLabelArgs $;

        public Builder() {
            $ = new DerivedLabelMetricLabelConstructedLabelArgs();
        }

        public Builder(DerivedLabelMetricLabelConstructedLabelArgs defaults) {
            $ = new DerivedLabelMetricLabelConstructedLabelArgs(Objects.requireNonNull(defaults));
        }

        public Builder valueDefinitions(Output<List<DerivedLabelMetricLabelConstructedLabelValueDefinitionArgs>> valueDefinitions) {
            $.valueDefinitions = valueDefinitions;
            return this;
        }

        public Builder valueDefinitions(List<DerivedLabelMetricLabelConstructedLabelValueDefinitionArgs> valueDefinitions) {
            return valueDefinitions(Output.of(valueDefinitions));
        }

        public Builder valueDefinitions(DerivedLabelMetricLabelConstructedLabelValueDefinitionArgs... valueDefinitions) {
            return valueDefinitions(List.of(valueDefinitions));
        }

        public DerivedLabelMetricLabelConstructedLabelArgs build() {
            $.valueDefinitions = Objects.requireNonNull($.valueDefinitions, "expected parameter 'valueDefinitions' to be non-null");
            return $;
        }
    }

}
