// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.chronosphere.chronosphere.inputs.LogControlConfigRuleDropFieldParentPathArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LogControlConfigRuleDropFieldArgs extends com.pulumi.resources.ResourceArgs {

    public static final LogControlConfigRuleDropFieldArgs Empty = new LogControlConfigRuleDropFieldArgs();

    @Import(name="fieldRegex")
    private @Nullable Output<String> fieldRegex;

    public Optional<Output<String>> fieldRegex() {
        return Optional.ofNullable(this.fieldRegex);
    }

    @Import(name="parentPath")
    private @Nullable Output<LogControlConfigRuleDropFieldParentPathArgs> parentPath;

    public Optional<Output<LogControlConfigRuleDropFieldParentPathArgs>> parentPath() {
        return Optional.ofNullable(this.parentPath);
    }

    private LogControlConfigRuleDropFieldArgs() {}

    private LogControlConfigRuleDropFieldArgs(LogControlConfigRuleDropFieldArgs $) {
        this.fieldRegex = $.fieldRegex;
        this.parentPath = $.parentPath;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LogControlConfigRuleDropFieldArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LogControlConfigRuleDropFieldArgs $;

        public Builder() {
            $ = new LogControlConfigRuleDropFieldArgs();
        }

        public Builder(LogControlConfigRuleDropFieldArgs defaults) {
            $ = new LogControlConfigRuleDropFieldArgs(Objects.requireNonNull(defaults));
        }

        public Builder fieldRegex(@Nullable Output<String> fieldRegex) {
            $.fieldRegex = fieldRegex;
            return this;
        }

        public Builder fieldRegex(String fieldRegex) {
            return fieldRegex(Output.of(fieldRegex));
        }

        public Builder parentPath(@Nullable Output<LogControlConfigRuleDropFieldParentPathArgs> parentPath) {
            $.parentPath = parentPath;
            return this;
        }

        public Builder parentPath(LogControlConfigRuleDropFieldParentPathArgs parentPath) {
            return parentPath(Output.of(parentPath));
        }

        public LogControlConfigRuleDropFieldArgs build() {
            return $;
        }
    }

}
