// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import io.chronosphere.chronosphere.inputs.LogIngestConfigFieldNormalizationCustomFieldNormalizationArgs;
import io.chronosphere.chronosphere.inputs.LogIngestConfigFieldNormalizationMessageArgs;
import io.chronosphere.chronosphere.inputs.LogIngestConfigFieldNormalizationServiceArgs;
import io.chronosphere.chronosphere.inputs.LogIngestConfigFieldNormalizationSeverityArgs;
import io.chronosphere.chronosphere.inputs.LogIngestConfigFieldNormalizationTimestampArgs;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LogIngestConfigFieldNormalizationArgs extends com.pulumi.resources.ResourceArgs {

    public static final LogIngestConfigFieldNormalizationArgs Empty = new LogIngestConfigFieldNormalizationArgs();

    @Import(name="customFieldNormalizations")
    private @Nullable Output<List<LogIngestConfigFieldNormalizationCustomFieldNormalizationArgs>> customFieldNormalizations;

    public Optional<Output<List<LogIngestConfigFieldNormalizationCustomFieldNormalizationArgs>>> customFieldNormalizations() {
        return Optional.ofNullable(this.customFieldNormalizations);
    }

    @Import(name="message")
    private @Nullable Output<LogIngestConfigFieldNormalizationMessageArgs> message;

    public Optional<Output<LogIngestConfigFieldNormalizationMessageArgs>> message() {
        return Optional.ofNullable(this.message);
    }

    @Import(name="service")
    private @Nullable Output<LogIngestConfigFieldNormalizationServiceArgs> service;

    public Optional<Output<LogIngestConfigFieldNormalizationServiceArgs>> service() {
        return Optional.ofNullable(this.service);
    }

    @Import(name="severity")
    private @Nullable Output<LogIngestConfigFieldNormalizationSeverityArgs> severity;

    public Optional<Output<LogIngestConfigFieldNormalizationSeverityArgs>> severity() {
        return Optional.ofNullable(this.severity);
    }

    @Import(name="timestamp")
    private @Nullable Output<LogIngestConfigFieldNormalizationTimestampArgs> timestamp;

    public Optional<Output<LogIngestConfigFieldNormalizationTimestampArgs>> timestamp() {
        return Optional.ofNullable(this.timestamp);
    }

    private LogIngestConfigFieldNormalizationArgs() {}

    private LogIngestConfigFieldNormalizationArgs(LogIngestConfigFieldNormalizationArgs $) {
        this.customFieldNormalizations = $.customFieldNormalizations;
        this.message = $.message;
        this.service = $.service;
        this.severity = $.severity;
        this.timestamp = $.timestamp;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LogIngestConfigFieldNormalizationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LogIngestConfigFieldNormalizationArgs $;

        public Builder() {
            $ = new LogIngestConfigFieldNormalizationArgs();
        }

        public Builder(LogIngestConfigFieldNormalizationArgs defaults) {
            $ = new LogIngestConfigFieldNormalizationArgs(Objects.requireNonNull(defaults));
        }

        public Builder customFieldNormalizations(@Nullable Output<List<LogIngestConfigFieldNormalizationCustomFieldNormalizationArgs>> customFieldNormalizations) {
            $.customFieldNormalizations = customFieldNormalizations;
            return this;
        }

        public Builder customFieldNormalizations(List<LogIngestConfigFieldNormalizationCustomFieldNormalizationArgs> customFieldNormalizations) {
            return customFieldNormalizations(Output.of(customFieldNormalizations));
        }

        public Builder customFieldNormalizations(LogIngestConfigFieldNormalizationCustomFieldNormalizationArgs... customFieldNormalizations) {
            return customFieldNormalizations(List.of(customFieldNormalizations));
        }

        public Builder message(@Nullable Output<LogIngestConfigFieldNormalizationMessageArgs> message) {
            $.message = message;
            return this;
        }

        public Builder message(LogIngestConfigFieldNormalizationMessageArgs message) {
            return message(Output.of(message));
        }

        public Builder service(@Nullable Output<LogIngestConfigFieldNormalizationServiceArgs> service) {
            $.service = service;
            return this;
        }

        public Builder service(LogIngestConfigFieldNormalizationServiceArgs service) {
            return service(Output.of(service));
        }

        public Builder severity(@Nullable Output<LogIngestConfigFieldNormalizationSeverityArgs> severity) {
            $.severity = severity;
            return this;
        }

        public Builder severity(LogIngestConfigFieldNormalizationSeverityArgs severity) {
            return severity(Output.of(severity));
        }

        public Builder timestamp(@Nullable Output<LogIngestConfigFieldNormalizationTimestampArgs> timestamp) {
            $.timestamp = timestamp;
            return this;
        }

        public Builder timestamp(LogIngestConfigFieldNormalizationTimestampArgs timestamp) {
            return timestamp(Output.of(timestamp));
        }

        public LogIngestConfigFieldNormalizationArgs build() {
            return $;
        }
    }

}
