// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LogscaleActionSlackActionArgs extends com.pulumi.resources.ResourceArgs {

    public static final LogscaleActionSlackActionArgs Empty = new LogscaleActionSlackActionArgs();

    @Import(name="fields")
    private @Nullable Output<Map<String,String>> fields;

    public Optional<Output<Map<String,String>>> fields() {
        return Optional.ofNullable(this.fields);
    }

    @Import(name="url", required=true)
    private Output<String> url;

    public Output<String> url() {
        return this.url;
    }

    @Import(name="useProxy")
    private @Nullable Output<Boolean> useProxy;

    public Optional<Output<Boolean>> useProxy() {
        return Optional.ofNullable(this.useProxy);
    }

    private LogscaleActionSlackActionArgs() {}

    private LogscaleActionSlackActionArgs(LogscaleActionSlackActionArgs $) {
        this.fields = $.fields;
        this.url = $.url;
        this.useProxy = $.useProxy;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LogscaleActionSlackActionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LogscaleActionSlackActionArgs $;

        public Builder() {
            $ = new LogscaleActionSlackActionArgs();
        }

        public Builder(LogscaleActionSlackActionArgs defaults) {
            $ = new LogscaleActionSlackActionArgs(Objects.requireNonNull(defaults));
        }

        public Builder fields(@Nullable Output<Map<String,String>> fields) {
            $.fields = fields;
            return this;
        }

        public Builder fields(Map<String,String> fields) {
            return fields(Output.of(fields));
        }

        public Builder url(Output<String> url) {
            $.url = url;
            return this;
        }

        public Builder url(String url) {
            return url(Output.of(url));
        }

        public Builder useProxy(@Nullable Output<Boolean> useProxy) {
            $.useProxy = useProxy;
            return this;
        }

        public Builder useProxy(Boolean useProxy) {
            return useProxy(Output.of(useProxy));
        }

        public LogscaleActionSlackActionArgs build() {
            $.url = Objects.requireNonNull($.url, "expected parameter 'url' to be non-null");
            return $;
        }
    }

}
