// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class NotificationPolicyRouteDestinationEmailArgs extends com.pulumi.resources.ResourceArgs {

    public static final NotificationPolicyRouteDestinationEmailArgs Empty = new NotificationPolicyRouteDestinationEmailArgs();

    @Import(name="addresses", required=true)
    private Output<List<String>> addresses;

    public Output<List<String>> addresses() {
        return this.addresses;
    }

    private NotificationPolicyRouteDestinationEmailArgs() {}

    private NotificationPolicyRouteDestinationEmailArgs(NotificationPolicyRouteDestinationEmailArgs $) {
        this.addresses = $.addresses;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NotificationPolicyRouteDestinationEmailArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NotificationPolicyRouteDestinationEmailArgs $;

        public Builder() {
            $ = new NotificationPolicyRouteDestinationEmailArgs();
        }

        public Builder(NotificationPolicyRouteDestinationEmailArgs defaults) {
            $ = new NotificationPolicyRouteDestinationEmailArgs(Objects.requireNonNull(defaults));
        }

        public Builder addresses(Output<List<String>> addresses) {
            $.addresses = addresses;
            return this;
        }

        public Builder addresses(List<String> addresses) {
            return addresses(Output.of(addresses));
        }

        public Builder addresses(String... addresses) {
            return addresses(List.of(addresses));
        }

        public NotificationPolicyRouteDestinationEmailArgs build() {
            $.addresses = Objects.requireNonNull($.addresses, "expected parameter 'addresses' to be non-null");
            return $;
        }
    }

}
