// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class NotificationPolicyOverrideRouteDestinationPagerdutyArgs extends com.pulumi.resources.ResourceArgs {

    public static final NotificationPolicyOverrideRouteDestinationPagerdutyArgs Empty = new NotificationPolicyOverrideRouteDestinationPagerdutyArgs();

    @Import(name="externalConnectionSlug", required=true)
    private Output<String> externalConnectionSlug;

    public Output<String> externalConnectionSlug() {
        return this.externalConnectionSlug;
    }

    private NotificationPolicyOverrideRouteDestinationPagerdutyArgs() {}

    private NotificationPolicyOverrideRouteDestinationPagerdutyArgs(NotificationPolicyOverrideRouteDestinationPagerdutyArgs $) {
        this.externalConnectionSlug = $.externalConnectionSlug;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NotificationPolicyOverrideRouteDestinationPagerdutyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NotificationPolicyOverrideRouteDestinationPagerdutyArgs $;

        public Builder() {
            $ = new NotificationPolicyOverrideRouteDestinationPagerdutyArgs();
        }

        public Builder(NotificationPolicyOverrideRouteDestinationPagerdutyArgs defaults) {
            $ = new NotificationPolicyOverrideRouteDestinationPagerdutyArgs(Objects.requireNonNull(defaults));
        }

        public Builder externalConnectionSlug(Output<String> externalConnectionSlug) {
            $.externalConnectionSlug = externalConnectionSlug;
            return this;
        }

        public Builder externalConnectionSlug(String externalConnectionSlug) {
            return externalConnectionSlug(Output.of(externalConnectionSlug));
        }

        public NotificationPolicyOverrideRouteDestinationPagerdutyArgs build() {
            $.externalConnectionSlug = Objects.requireNonNull($.externalConnectionSlug, "expected parameter 'externalConnectionSlug' to be non-null");
            return $;
        }
    }

}
