// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SlackExternalConnectionState extends com.pulumi.resources.ResourceArgs {

    public static final SlackExternalConnectionState Empty = new SlackExternalConnectionState();

    @Import(name="apiUrl")
    private @Nullable Output<String> apiUrl;

    public Optional<Output<String>> apiUrl() {
        return Optional.ofNullable(this.apiUrl);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="slug")
    private @Nullable Output<String> slug;

    public Optional<Output<String>> slug() {
        return Optional.ofNullable(this.slug);
    }

    @Import(name="token")
    private @Nullable Output<String> token;

    public Optional<Output<String>> token() {
        return Optional.ofNullable(this.token);
    }

    private SlackExternalConnectionState() {}

    private SlackExternalConnectionState(SlackExternalConnectionState $) {
        this.apiUrl = $.apiUrl;
        this.name = $.name;
        this.slug = $.slug;
        this.token = $.token;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SlackExternalConnectionState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SlackExternalConnectionState $;

        public Builder() {
            $ = new SlackExternalConnectionState();
        }

        public Builder(SlackExternalConnectionState defaults) {
            $ = new SlackExternalConnectionState(Objects.requireNonNull(defaults));
        }

        public Builder apiUrl(@Nullable Output<String> apiUrl) {
            $.apiUrl = apiUrl;
            return this;
        }

        public Builder apiUrl(String apiUrl) {
            return apiUrl(Output.of(apiUrl));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder slug(@Nullable Output<String> slug) {
            $.slug = slug;
            return this;
        }

        public Builder slug(String slug) {
            return slug(Output.of(slug));
        }

        public Builder token(@Nullable Output<String> token) {
            $.token = token;
            return this;
        }

        public Builder token(String token) {
            return token(Output.of(token));
        }

        public SlackExternalConnectionState build() {
            return $;
        }
    }

}
