// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SLOSliCustomIndicatorArgs extends com.pulumi.resources.ResourceArgs {

    public static final SLOSliCustomIndicatorArgs Empty = new SLOSliCustomIndicatorArgs();

    @Import(name="badQueryTemplate")
    private @Nullable Output<String> badQueryTemplate;

    public Optional<Output<String>> badQueryTemplate() {
        return Optional.ofNullable(this.badQueryTemplate);
    }

    @Import(name="goodQueryTemplate")
    private @Nullable Output<String> goodQueryTemplate;

    public Optional<Output<String>> goodQueryTemplate() {
        return Optional.ofNullable(this.goodQueryTemplate);
    }

    @Import(name="totalQueryTemplate", required=true)
    private Output<String> totalQueryTemplate;

    public Output<String> totalQueryTemplate() {
        return this.totalQueryTemplate;
    }

    private SLOSliCustomIndicatorArgs() {}

    private SLOSliCustomIndicatorArgs(SLOSliCustomIndicatorArgs $) {
        this.badQueryTemplate = $.badQueryTemplate;
        this.goodQueryTemplate = $.goodQueryTemplate;
        this.totalQueryTemplate = $.totalQueryTemplate;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SLOSliCustomIndicatorArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SLOSliCustomIndicatorArgs $;

        public Builder() {
            $ = new SLOSliCustomIndicatorArgs();
        }

        public Builder(SLOSliCustomIndicatorArgs defaults) {
            $ = new SLOSliCustomIndicatorArgs(Objects.requireNonNull(defaults));
        }

        public Builder badQueryTemplate(@Nullable Output<String> badQueryTemplate) {
            $.badQueryTemplate = badQueryTemplate;
            return this;
        }

        public Builder badQueryTemplate(String badQueryTemplate) {
            return badQueryTemplate(Output.of(badQueryTemplate));
        }

        public Builder goodQueryTemplate(@Nullable Output<String> goodQueryTemplate) {
            $.goodQueryTemplate = goodQueryTemplate;
            return this;
        }

        public Builder goodQueryTemplate(String goodQueryTemplate) {
            return goodQueryTemplate(Output.of(goodQueryTemplate));
        }

        public Builder totalQueryTemplate(Output<String> totalQueryTemplate) {
            $.totalQueryTemplate = totalQueryTemplate;
            return this;
        }

        public Builder totalQueryTemplate(String totalQueryTemplate) {
            return totalQueryTemplate(Output.of(totalQueryTemplate));
        }

        public SLOSliCustomIndicatorArgs build() {
            $.totalQueryTemplate = Objects.requireNonNull($.totalQueryTemplate, "expected parameter 'totalQueryTemplate' to be non-null");
            return $;
        }
    }

}
