// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.chronosphere.chronosphere.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TraceMetricsRuleGroupByKeyArgs extends com.pulumi.resources.ResourceArgs {

    public static final TraceMetricsRuleGroupByKeyArgs Empty = new TraceMetricsRuleGroupByKeyArgs();

    @Import(name="namedKey")
    private @Nullable Output<String> namedKey;

    public Optional<Output<String>> namedKey() {
        return Optional.ofNullable(this.namedKey);
    }

    @Import(name="type", required=true)
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }

    private TraceMetricsRuleGroupByKeyArgs() {}

    private TraceMetricsRuleGroupByKeyArgs(TraceMetricsRuleGroupByKeyArgs $) {
        this.namedKey = $.namedKey;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TraceMetricsRuleGroupByKeyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TraceMetricsRuleGroupByKeyArgs $;

        public Builder() {
            $ = new TraceMetricsRuleGroupByKeyArgs();
        }

        public Builder(TraceMetricsRuleGroupByKeyArgs defaults) {
            $ = new TraceMetricsRuleGroupByKeyArgs(Objects.requireNonNull(defaults));
        }

        public Builder namedKey(@Nullable Output<String> namedKey) {
            $.namedKey = namedKey;
            return this;
        }

        public Builder namedKey(String namedKey) {
            return namedKey(Output.of(namedKey));
        }

        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public TraceMetricsRuleGroupByKeyArgs build() {
            $.type = Objects.requireNonNull($.type, "expected parameter 'type' to be non-null");
            return $;
        }
    }

}
