// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package chronosphere

import (
	"context"
	"reflect"

	"errors"
	"github.com/chronosphereio/pulumi-chronosphere/sdk/go/chronosphere/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PagerdutyExternalConnection struct {
	pulumi.CustomResourceState

	Name                   pulumi.StringOutput    `pulumi:"name"`
	PagerdutyApiKey        pulumi.StringPtrOutput `pulumi:"pagerdutyApiKey"`
	PagerdutyEventsVersion pulumi.StringPtrOutput `pulumi:"pagerdutyEventsVersion"`
	Slug                   pulumi.StringOutput    `pulumi:"slug"`
}

// NewPagerdutyExternalConnection registers a new resource with the given unique name, arguments, and options.
func NewPagerdutyExternalConnection(ctx *pulumi.Context,
	name string, args *PagerdutyExternalConnectionArgs, opts ...pulumi.ResourceOption) (*PagerdutyExternalConnection, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.PagerdutyApiKey != nil {
		args.PagerdutyApiKey = pulumi.ToSecret(args.PagerdutyApiKey).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"pagerdutyApiKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PagerdutyExternalConnection
	err := ctx.RegisterResource("chronosphere:index/pagerdutyExternalConnection:PagerdutyExternalConnection", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPagerdutyExternalConnection gets an existing PagerdutyExternalConnection resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPagerdutyExternalConnection(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PagerdutyExternalConnectionState, opts ...pulumi.ResourceOption) (*PagerdutyExternalConnection, error) {
	var resource PagerdutyExternalConnection
	err := ctx.ReadResource("chronosphere:index/pagerdutyExternalConnection:PagerdutyExternalConnection", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PagerdutyExternalConnection resources.
type pagerdutyExternalConnectionState struct {
	Name                   *string `pulumi:"name"`
	PagerdutyApiKey        *string `pulumi:"pagerdutyApiKey"`
	PagerdutyEventsVersion *string `pulumi:"pagerdutyEventsVersion"`
	Slug                   *string `pulumi:"slug"`
}

type PagerdutyExternalConnectionState struct {
	Name                   pulumi.StringPtrInput
	PagerdutyApiKey        pulumi.StringPtrInput
	PagerdutyEventsVersion pulumi.StringPtrInput
	Slug                   pulumi.StringPtrInput
}

func (PagerdutyExternalConnectionState) ElementType() reflect.Type {
	return reflect.TypeOf((*pagerdutyExternalConnectionState)(nil)).Elem()
}

type pagerdutyExternalConnectionArgs struct {
	Name                   string  `pulumi:"name"`
	PagerdutyApiKey        *string `pulumi:"pagerdutyApiKey"`
	PagerdutyEventsVersion *string `pulumi:"pagerdutyEventsVersion"`
	Slug                   *string `pulumi:"slug"`
}

// The set of arguments for constructing a PagerdutyExternalConnection resource.
type PagerdutyExternalConnectionArgs struct {
	Name                   pulumi.StringInput
	PagerdutyApiKey        pulumi.StringPtrInput
	PagerdutyEventsVersion pulumi.StringPtrInput
	Slug                   pulumi.StringPtrInput
}

func (PagerdutyExternalConnectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*pagerdutyExternalConnectionArgs)(nil)).Elem()
}

type PagerdutyExternalConnectionInput interface {
	pulumi.Input

	ToPagerdutyExternalConnectionOutput() PagerdutyExternalConnectionOutput
	ToPagerdutyExternalConnectionOutputWithContext(ctx context.Context) PagerdutyExternalConnectionOutput
}

func (*PagerdutyExternalConnection) ElementType() reflect.Type {
	return reflect.TypeOf((**PagerdutyExternalConnection)(nil)).Elem()
}

func (i *PagerdutyExternalConnection) ToPagerdutyExternalConnectionOutput() PagerdutyExternalConnectionOutput {
	return i.ToPagerdutyExternalConnectionOutputWithContext(context.Background())
}

func (i *PagerdutyExternalConnection) ToPagerdutyExternalConnectionOutputWithContext(ctx context.Context) PagerdutyExternalConnectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PagerdutyExternalConnectionOutput)
}

// PagerdutyExternalConnectionArrayInput is an input type that accepts PagerdutyExternalConnectionArray and PagerdutyExternalConnectionArrayOutput values.
// You can construct a concrete instance of `PagerdutyExternalConnectionArrayInput` via:
//
//	PagerdutyExternalConnectionArray{ PagerdutyExternalConnectionArgs{...} }
type PagerdutyExternalConnectionArrayInput interface {
	pulumi.Input

	ToPagerdutyExternalConnectionArrayOutput() PagerdutyExternalConnectionArrayOutput
	ToPagerdutyExternalConnectionArrayOutputWithContext(context.Context) PagerdutyExternalConnectionArrayOutput
}

type PagerdutyExternalConnectionArray []PagerdutyExternalConnectionInput

func (PagerdutyExternalConnectionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PagerdutyExternalConnection)(nil)).Elem()
}

func (i PagerdutyExternalConnectionArray) ToPagerdutyExternalConnectionArrayOutput() PagerdutyExternalConnectionArrayOutput {
	return i.ToPagerdutyExternalConnectionArrayOutputWithContext(context.Background())
}

func (i PagerdutyExternalConnectionArray) ToPagerdutyExternalConnectionArrayOutputWithContext(ctx context.Context) PagerdutyExternalConnectionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PagerdutyExternalConnectionArrayOutput)
}

// PagerdutyExternalConnectionMapInput is an input type that accepts PagerdutyExternalConnectionMap and PagerdutyExternalConnectionMapOutput values.
// You can construct a concrete instance of `PagerdutyExternalConnectionMapInput` via:
//
//	PagerdutyExternalConnectionMap{ "key": PagerdutyExternalConnectionArgs{...} }
type PagerdutyExternalConnectionMapInput interface {
	pulumi.Input

	ToPagerdutyExternalConnectionMapOutput() PagerdutyExternalConnectionMapOutput
	ToPagerdutyExternalConnectionMapOutputWithContext(context.Context) PagerdutyExternalConnectionMapOutput
}

type PagerdutyExternalConnectionMap map[string]PagerdutyExternalConnectionInput

func (PagerdutyExternalConnectionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PagerdutyExternalConnection)(nil)).Elem()
}

func (i PagerdutyExternalConnectionMap) ToPagerdutyExternalConnectionMapOutput() PagerdutyExternalConnectionMapOutput {
	return i.ToPagerdutyExternalConnectionMapOutputWithContext(context.Background())
}

func (i PagerdutyExternalConnectionMap) ToPagerdutyExternalConnectionMapOutputWithContext(ctx context.Context) PagerdutyExternalConnectionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PagerdutyExternalConnectionMapOutput)
}

type PagerdutyExternalConnectionOutput struct{ *pulumi.OutputState }

func (PagerdutyExternalConnectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PagerdutyExternalConnection)(nil)).Elem()
}

func (o PagerdutyExternalConnectionOutput) ToPagerdutyExternalConnectionOutput() PagerdutyExternalConnectionOutput {
	return o
}

func (o PagerdutyExternalConnectionOutput) ToPagerdutyExternalConnectionOutputWithContext(ctx context.Context) PagerdutyExternalConnectionOutput {
	return o
}

func (o PagerdutyExternalConnectionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *PagerdutyExternalConnection) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o PagerdutyExternalConnectionOutput) PagerdutyApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PagerdutyExternalConnection) pulumi.StringPtrOutput { return v.PagerdutyApiKey }).(pulumi.StringPtrOutput)
}

func (o PagerdutyExternalConnectionOutput) PagerdutyEventsVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PagerdutyExternalConnection) pulumi.StringPtrOutput { return v.PagerdutyEventsVersion }).(pulumi.StringPtrOutput)
}

func (o PagerdutyExternalConnectionOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v *PagerdutyExternalConnection) pulumi.StringOutput { return v.Slug }).(pulumi.StringOutput)
}

type PagerdutyExternalConnectionArrayOutput struct{ *pulumi.OutputState }

func (PagerdutyExternalConnectionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PagerdutyExternalConnection)(nil)).Elem()
}

func (o PagerdutyExternalConnectionArrayOutput) ToPagerdutyExternalConnectionArrayOutput() PagerdutyExternalConnectionArrayOutput {
	return o
}

func (o PagerdutyExternalConnectionArrayOutput) ToPagerdutyExternalConnectionArrayOutputWithContext(ctx context.Context) PagerdutyExternalConnectionArrayOutput {
	return o
}

func (o PagerdutyExternalConnectionArrayOutput) Index(i pulumi.IntInput) PagerdutyExternalConnectionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PagerdutyExternalConnection {
		return vs[0].([]*PagerdutyExternalConnection)[vs[1].(int)]
	}).(PagerdutyExternalConnectionOutput)
}

type PagerdutyExternalConnectionMapOutput struct{ *pulumi.OutputState }

func (PagerdutyExternalConnectionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PagerdutyExternalConnection)(nil)).Elem()
}

func (o PagerdutyExternalConnectionMapOutput) ToPagerdutyExternalConnectionMapOutput() PagerdutyExternalConnectionMapOutput {
	return o
}

func (o PagerdutyExternalConnectionMapOutput) ToPagerdutyExternalConnectionMapOutputWithContext(ctx context.Context) PagerdutyExternalConnectionMapOutput {
	return o
}

func (o PagerdutyExternalConnectionMapOutput) MapIndex(k pulumi.StringInput) PagerdutyExternalConnectionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PagerdutyExternalConnection {
		return vs[0].(map[string]*PagerdutyExternalConnection)[vs[1].(string)]
	}).(PagerdutyExternalConnectionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PagerdutyExternalConnectionInput)(nil)).Elem(), &PagerdutyExternalConnection{})
	pulumi.RegisterInputType(reflect.TypeOf((*PagerdutyExternalConnectionArrayInput)(nil)).Elem(), PagerdutyExternalConnectionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PagerdutyExternalConnectionMapInput)(nil)).Elem(), PagerdutyExternalConnectionMap{})
	pulumi.RegisterOutputType(PagerdutyExternalConnectionOutput{})
	pulumi.RegisterOutputType(PagerdutyExternalConnectionArrayOutput{})
	pulumi.RegisterOutputType(PagerdutyExternalConnectionMapOutput{})
}
