// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package chronosphere

import (
	"context"
	"reflect"

	"errors"
	"github.com/chronosphereio/pulumi-chronosphere/sdk/go/chronosphere/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ServiceAttribute struct {
	pulumi.CustomResourceState

	// Human-readable description of the service
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Name of the service
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// Notification policy ID for alerts
	NotificationPolicyId pulumi.StringPtrOutput `pulumi:"notificationPolicyId"`
	// The slug of the service to associate attributes with
	ServiceSlug pulumi.StringOutput `pulumi:"serviceSlug"`
	// Team that owns the service
	TeamId pulumi.StringPtrOutput `pulumi:"teamId"`
}

// NewServiceAttribute registers a new resource with the given unique name, arguments, and options.
func NewServiceAttribute(ctx *pulumi.Context,
	name string, args *ServiceAttributeArgs, opts ...pulumi.ResourceOption) (*ServiceAttribute, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ServiceSlug == nil {
		return nil, errors.New("invalid value for required argument 'ServiceSlug'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ServiceAttribute
	err := ctx.RegisterResource("chronosphere:index/serviceAttribute:ServiceAttribute", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServiceAttribute gets an existing ServiceAttribute resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServiceAttribute(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServiceAttributeState, opts ...pulumi.ResourceOption) (*ServiceAttribute, error) {
	var resource ServiceAttribute
	err := ctx.ReadResource("chronosphere:index/serviceAttribute:ServiceAttribute", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ServiceAttribute resources.
type serviceAttributeState struct {
	// Human-readable description of the service
	Description *string `pulumi:"description"`
	// Name of the service
	Name *string `pulumi:"name"`
	// Notification policy ID for alerts
	NotificationPolicyId *string `pulumi:"notificationPolicyId"`
	// The slug of the service to associate attributes with
	ServiceSlug *string `pulumi:"serviceSlug"`
	// Team that owns the service
	TeamId *string `pulumi:"teamId"`
}

type ServiceAttributeState struct {
	// Human-readable description of the service
	Description pulumi.StringPtrInput
	// Name of the service
	Name pulumi.StringPtrInput
	// Notification policy ID for alerts
	NotificationPolicyId pulumi.StringPtrInput
	// The slug of the service to associate attributes with
	ServiceSlug pulumi.StringPtrInput
	// Team that owns the service
	TeamId pulumi.StringPtrInput
}

func (ServiceAttributeState) ElementType() reflect.Type {
	return reflect.TypeOf((*serviceAttributeState)(nil)).Elem()
}

type serviceAttributeArgs struct {
	// Human-readable description of the service
	Description *string `pulumi:"description"`
	// Name of the service
	Name *string `pulumi:"name"`
	// Notification policy ID for alerts
	NotificationPolicyId *string `pulumi:"notificationPolicyId"`
	// The slug of the service to associate attributes with
	ServiceSlug string `pulumi:"serviceSlug"`
	// Team that owns the service
	TeamId *string `pulumi:"teamId"`
}

// The set of arguments for constructing a ServiceAttribute resource.
type ServiceAttributeArgs struct {
	// Human-readable description of the service
	Description pulumi.StringPtrInput
	// Name of the service
	Name pulumi.StringPtrInput
	// Notification policy ID for alerts
	NotificationPolicyId pulumi.StringPtrInput
	// The slug of the service to associate attributes with
	ServiceSlug pulumi.StringInput
	// Team that owns the service
	TeamId pulumi.StringPtrInput
}

func (ServiceAttributeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serviceAttributeArgs)(nil)).Elem()
}

type ServiceAttributeInput interface {
	pulumi.Input

	ToServiceAttributeOutput() ServiceAttributeOutput
	ToServiceAttributeOutputWithContext(ctx context.Context) ServiceAttributeOutput
}

func (*ServiceAttribute) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceAttribute)(nil)).Elem()
}

func (i *ServiceAttribute) ToServiceAttributeOutput() ServiceAttributeOutput {
	return i.ToServiceAttributeOutputWithContext(context.Background())
}

func (i *ServiceAttribute) ToServiceAttributeOutputWithContext(ctx context.Context) ServiceAttributeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceAttributeOutput)
}

// ServiceAttributeArrayInput is an input type that accepts ServiceAttributeArray and ServiceAttributeArrayOutput values.
// You can construct a concrete instance of `ServiceAttributeArrayInput` via:
//
//	ServiceAttributeArray{ ServiceAttributeArgs{...} }
type ServiceAttributeArrayInput interface {
	pulumi.Input

	ToServiceAttributeArrayOutput() ServiceAttributeArrayOutput
	ToServiceAttributeArrayOutputWithContext(context.Context) ServiceAttributeArrayOutput
}

type ServiceAttributeArray []ServiceAttributeInput

func (ServiceAttributeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServiceAttribute)(nil)).Elem()
}

func (i ServiceAttributeArray) ToServiceAttributeArrayOutput() ServiceAttributeArrayOutput {
	return i.ToServiceAttributeArrayOutputWithContext(context.Background())
}

func (i ServiceAttributeArray) ToServiceAttributeArrayOutputWithContext(ctx context.Context) ServiceAttributeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceAttributeArrayOutput)
}

// ServiceAttributeMapInput is an input type that accepts ServiceAttributeMap and ServiceAttributeMapOutput values.
// You can construct a concrete instance of `ServiceAttributeMapInput` via:
//
//	ServiceAttributeMap{ "key": ServiceAttributeArgs{...} }
type ServiceAttributeMapInput interface {
	pulumi.Input

	ToServiceAttributeMapOutput() ServiceAttributeMapOutput
	ToServiceAttributeMapOutputWithContext(context.Context) ServiceAttributeMapOutput
}

type ServiceAttributeMap map[string]ServiceAttributeInput

func (ServiceAttributeMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServiceAttribute)(nil)).Elem()
}

func (i ServiceAttributeMap) ToServiceAttributeMapOutput() ServiceAttributeMapOutput {
	return i.ToServiceAttributeMapOutputWithContext(context.Background())
}

func (i ServiceAttributeMap) ToServiceAttributeMapOutputWithContext(ctx context.Context) ServiceAttributeMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceAttributeMapOutput)
}

type ServiceAttributeOutput struct{ *pulumi.OutputState }

func (ServiceAttributeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceAttribute)(nil)).Elem()
}

func (o ServiceAttributeOutput) ToServiceAttributeOutput() ServiceAttributeOutput {
	return o
}

func (o ServiceAttributeOutput) ToServiceAttributeOutputWithContext(ctx context.Context) ServiceAttributeOutput {
	return o
}

// Human-readable description of the service
func (o ServiceAttributeOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServiceAttribute) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Name of the service
func (o ServiceAttributeOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServiceAttribute) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// Notification policy ID for alerts
func (o ServiceAttributeOutput) NotificationPolicyId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServiceAttribute) pulumi.StringPtrOutput { return v.NotificationPolicyId }).(pulumi.StringPtrOutput)
}

// The slug of the service to associate attributes with
func (o ServiceAttributeOutput) ServiceSlug() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceAttribute) pulumi.StringOutput { return v.ServiceSlug }).(pulumi.StringOutput)
}

// Team that owns the service
func (o ServiceAttributeOutput) TeamId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServiceAttribute) pulumi.StringPtrOutput { return v.TeamId }).(pulumi.StringPtrOutput)
}

type ServiceAttributeArrayOutput struct{ *pulumi.OutputState }

func (ServiceAttributeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServiceAttribute)(nil)).Elem()
}

func (o ServiceAttributeArrayOutput) ToServiceAttributeArrayOutput() ServiceAttributeArrayOutput {
	return o
}

func (o ServiceAttributeArrayOutput) ToServiceAttributeArrayOutputWithContext(ctx context.Context) ServiceAttributeArrayOutput {
	return o
}

func (o ServiceAttributeArrayOutput) Index(i pulumi.IntInput) ServiceAttributeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ServiceAttribute {
		return vs[0].([]*ServiceAttribute)[vs[1].(int)]
	}).(ServiceAttributeOutput)
}

type ServiceAttributeMapOutput struct{ *pulumi.OutputState }

func (ServiceAttributeMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServiceAttribute)(nil)).Elem()
}

func (o ServiceAttributeMapOutput) ToServiceAttributeMapOutput() ServiceAttributeMapOutput {
	return o
}

func (o ServiceAttributeMapOutput) ToServiceAttributeMapOutputWithContext(ctx context.Context) ServiceAttributeMapOutput {
	return o
}

func (o ServiceAttributeMapOutput) MapIndex(k pulumi.StringInput) ServiceAttributeOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ServiceAttribute {
		return vs[0].(map[string]*ServiceAttribute)[vs[1].(string)]
	}).(ServiceAttributeOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceAttributeInput)(nil)).Elem(), &ServiceAttribute{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceAttributeArrayInput)(nil)).Elem(), ServiceAttributeArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceAttributeMapInput)(nil)).Elem(), ServiceAttributeMap{})
	pulumi.RegisterOutputType(ServiceAttributeOutput{})
	pulumi.RegisterOutputType(ServiceAttributeArrayOutput{})
	pulumi.RegisterOutputType(ServiceAttributeMapOutput{})
}
