// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class ConsumptionConfigPartitionFilterConditionTraceSpanFilterIsRootSpanArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Boolean value the target field is compared against.
        /// </summary>
        [Input("value", required: true)]
        public Input<bool> Value { get; set; } = null!;

        public ConsumptionConfigPartitionFilterConditionTraceSpanFilterIsRootSpanArgs()
        {
        }
        public static new ConsumptionConfigPartitionFilterConditionTraceSpanFilterIsRootSpanArgs Empty => new ConsumptionConfigPartitionFilterConditionTraceSpanFilterIsRootSpanArgs();
    }
}
