// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class ConsumptionConfigPartitionPartitionPartitionFilterConditionArgs : global::Pulumi.ResourceArgs
    {
        [Input("datasetId")]
        public Input<string>? DatasetId { get; set; }

        [Input("logFilter")]
        public Input<Inputs.ConsumptionConfigPartitionPartitionPartitionFilterConditionLogFilterArgs>? LogFilter { get; set; }

        [Input("metricFilters")]
        private InputList<Inputs.ConsumptionConfigPartitionPartitionPartitionFilterConditionMetricFilterArgs>? _metricFilters;
        public InputList<Inputs.ConsumptionConfigPartitionPartitionPartitionFilterConditionMetricFilterArgs> MetricFilters
        {
            get => _metricFilters ?? (_metricFilters = new InputList<Inputs.ConsumptionConfigPartitionPartitionPartitionFilterConditionMetricFilterArgs>());
            set => _metricFilters = value;
        }

        [Input("traceFilter")]
        public Input<Inputs.ConsumptionConfigPartitionPartitionPartitionFilterConditionTraceFilterArgs>? TraceFilter { get; set; }

        public ConsumptionConfigPartitionPartitionPartitionFilterConditionArgs()
        {
        }
        public static new ConsumptionConfigPartitionPartitionPartitionFilterConditionArgs Empty => new ConsumptionConfigPartitionPartitionPartitionFilterConditionArgs();
    }
}
