// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class ConsumptionConfigPartitionPartitionPartitionPartitionPartitionFilterConditionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("datasetId")]
        public Input<string>? DatasetId { get; set; }

        [Input("logFilter")]
        public Input<Inputs.ConsumptionConfigPartitionPartitionPartitionPartitionPartitionFilterConditionLogFilterGetArgs>? LogFilter { get; set; }

        public ConsumptionConfigPartitionPartitionPartitionPartitionPartitionFilterConditionGetArgs()
        {
        }
        public static new ConsumptionConfigPartitionPartitionPartitionPartitionPartitionFilterConditionGetArgs Empty => new ConsumptionConfigPartitionPartitionPartitionPartitionPartitionFilterConditionGetArgs();
    }
}
