// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class ConsumptionBudgetThresholdArgs : global::Pulumi.ResourceArgs
    {
        [Input("action")]
        public Input<string>? Action { get; set; }

        [Input("instantRate")]
        public Input<Inputs.ConsumptionBudgetThresholdInstantRateArgs>? InstantRate { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("volume")]
        public Input<Inputs.ConsumptionBudgetThresholdVolumeArgs>? Volume { get; set; }

        public ConsumptionBudgetThresholdArgs()
        {
        }
        public static new ConsumptionBudgetThresholdArgs Empty => new ConsumptionBudgetThresholdArgs();
    }
}
