// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Chronosphere.Inputs
{

    public sealed class DatasetConfigurationTraceDatasetMatchCriteriaTraceErrorArgs : global::Pulumi.ResourceArgs
    {
        [Input("value", required: true)]
        public Input<bool> Value { get; set; } = null!;

        public DatasetConfigurationTraceDatasetMatchCriteriaTraceErrorArgs()
        {
        }
        public static new DatasetConfigurationTraceDatasetMatchCriteriaTraceErrorArgs Empty => new DatasetConfigurationTraceDatasetMatchCriteriaTraceErrorArgs();
    }
}
