// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class DerivedLabelSpanTagArgs : global::Pulumi.ResourceArgs
    {
        [Input("nameMappings")]
        private InputList<Inputs.DerivedLabelSpanTagNameMappingArgs>? _nameMappings;

        /// <summary>
        /// Ordered list of name mappings. The first mapping that matches supplies the derived label from its `source_tag`.
        /// </summary>
        public InputList<Inputs.DerivedLabelSpanTagNameMappingArgs> NameMappings
        {
            get => _nameMappings ?? (_nameMappings = new InputList<Inputs.DerivedLabelSpanTagNameMappingArgs>());
            set => _nameMappings = value;
        }

        public DerivedLabelSpanTagArgs()
        {
        }
        public static new DerivedLabelSpanTagArgs Empty => new DerivedLabelSpanTagArgs();
    }
}
