// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class LogControlConfigRuleParseFieldParserGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Grok parser configuration. Only set when `ParserType` is `GROK`.
        /// </summary>
        [Input("grokParser")]
        public Input<Inputs.LogControlConfigRuleParseFieldParserGrokParserGetArgs>? GrokParser { get; set; }

        /// <summary>
        /// Key/value parser configuration. Only set when `ParserType` is `KEY_VALUE`. Duplicate keys keep the first occurrence.
        /// </summary>
        [Input("keyValueParser")]
        public Input<Inputs.LogControlConfigRuleParseFieldParserKeyValueParserGetArgs>? KeyValueParser { get; set; }

        /// <summary>
        /// Type of parser to apply. Determines which of `RegexParser`, `KeyValueParser`, or `GrokParser` must be set.
        /// </summary>
        [Input("parserType", required: true)]
        public Input<string> ParserType { get; set; } = null!;

        /// <summary>
        /// Regex parser configuration. Only set when `ParserType` is `REGEX`.
        /// </summary>
        [Input("regexParser")]
        public Input<Inputs.LogControlConfigRuleParseFieldParserRegexParserGetArgs>? RegexParser { get; set; }

        public LogControlConfigRuleParseFieldParserGetArgs()
        {
        }
        public static new LogControlConfigRuleParseFieldParserGetArgs Empty => new LogControlConfigRuleParseFieldParserGetArgs();
    }
}
