// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class LogControlConfigRuleEmitMetricsGaugeValueArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Field path selector. Use `parent[child]` syntax to indicate nesting.
        /// </summary>
        [Input("selector")]
        public Input<string>? Selector { get; set; }

        public LogControlConfigRuleEmitMetricsGaugeValueArgs()
        {
        }
        public static new LogControlConfigRuleEmitMetricsGaugeValueArgs Empty => new LogControlConfigRuleEmitMetricsGaugeValueArgs();
    }
}
