// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class LogIngestConfigFieldNormalizationMessageArgs : global::Pulumi.ResourceArgs
    {
        [Input("defaultValue")]
        public Input<string>? DefaultValue { get; set; }

        [Input("sanitizePatterns")]
        private InputList<string>? _sanitizePatterns;
        public InputList<string> SanitizePatterns
        {
            get => _sanitizePatterns ?? (_sanitizePatterns = new InputList<string>());
            set => _sanitizePatterns = value;
        }

        [Input("sources")]
        private InputList<Inputs.LogIngestConfigFieldNormalizationMessageSourceArgs>? _sources;
        public InputList<Inputs.LogIngestConfigFieldNormalizationMessageSourceArgs> Sources
        {
            get => _sources ?? (_sources = new InputList<Inputs.LogIngestConfigFieldNormalizationMessageSourceArgs>());
            set => _sources = value;
        }

        [Input("valueMap")]
        private InputMap<string>? _valueMap;
        public InputMap<string> ValueMap
        {
            get => _valueMap ?? (_valueMap = new InputMap<string>());
            set => _valueMap = value;
        }

        public LogIngestConfigFieldNormalizationMessageArgs()
        {
        }
        public static new LogIngestConfigFieldNormalizationMessageArgs Empty => new LogIngestConfigFieldNormalizationMessageArgs();
    }
}
