// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class LogscaleActionEmailActionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("attachCsv")]
        public Input<bool>? AttachCsv { get; set; }

        [Input("bodyTemplate")]
        public Input<string>? BodyTemplate { get; set; }

        [Input("recipients", required: true)]
        private InputList<string>? _recipients;
        public InputList<string> Recipients
        {
            get => _recipients ?? (_recipients = new InputList<string>());
            set => _recipients = value;
        }

        [Input("subjectTemplate")]
        public Input<string>? SubjectTemplate { get; set; }

        [Input("useProxy")]
        public Input<bool>? UseProxy { get; set; }

        public LogscaleActionEmailActionGetArgs()
        {
        }
        public static new LogscaleActionEmailActionGetArgs Empty => new LogscaleActionEmailActionGetArgs();
    }
}
