// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class PagerdutyAlertNotifierLinkGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// URL the link points to.
        /// </summary>
        [Input("href", required: true)]
        public Input<string> Href { get; set; } = null!;

        /// <summary>
        /// Display text for the link.
        /// </summary>
        [Input("text")]
        public Input<string>? Text { get; set; }

        public PagerdutyAlertNotifierLinkGetArgs()
        {
        }
        public static new PagerdutyAlertNotifierLinkGetArgs Empty => new PagerdutyAlertNotifierLinkGetArgs();
    }
}
