// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class SlackAlertNotifierFieldArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If true, the field is short enough to be shown side-by-side with the next field.
        /// </summary>
        [Input("short")]
        public Input<bool>? Short { get; set; }

        /// <summary>
        /// Bold heading shown above the value.
        /// </summary>
        [Input("title")]
        public Input<string>? Title { get; set; }

        /// <summary>
        /// Value text. Supports Go templating.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public SlackAlertNotifierFieldArgs()
        {
        }
        public static new SlackAlertNotifierFieldArgs Empty => new SlackAlertNotifierFieldArgs();
    }
}
