// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class SLOSliGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("additionalPromqlFilters")]
        private InputList<Inputs.SLOSliAdditionalPromqlFilterGetArgs>? _additionalPromqlFilters;
        public InputList<Inputs.SLOSliAdditionalPromqlFilterGetArgs> AdditionalPromqlFilters
        {
            get => _additionalPromqlFilters ?? (_additionalPromqlFilters = new InputList<Inputs.SLOSliAdditionalPromqlFilterGetArgs>());
            set => _additionalPromqlFilters = value;
        }

        [Input("customDimensionLabels")]
        private InputList<string>? _customDimensionLabels;
        public InputList<string> CustomDimensionLabels
        {
            get => _customDimensionLabels ?? (_customDimensionLabels = new InputList<string>());
            set => _customDimensionLabels = value;
        }

        [Input("customIndicator")]
        public Input<Inputs.SLOSliCustomIndicatorGetArgs>? CustomIndicator { get; set; }

        [Input("customTimesliceIndicator")]
        public Input<Inputs.SLOSliCustomTimesliceIndicatorGetArgs>? CustomTimesliceIndicator { get; set; }

        public SLOSliGetArgs()
        {
        }
        public static new SLOSliGetArgs Empty => new SLOSliGetArgs();
    }
}
