// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class TraceTailSamplingRulesRuleFilterSpanIsRootSpanGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("value", required: true)]
        public Input<bool> Value { get; set; } = null!;

        public TraceTailSamplingRulesRuleFilterSpanIsRootSpanGetArgs()
        {
        }
        public static new TraceTailSamplingRulesRuleFilterSpanIsRootSpanGetArgs Empty => new TraceTailSamplingRulesRuleFilterSpanIsRootSpanGetArgs();
    }
}
