// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Inputs
{

    public sealed class TraceMetricsRuleTraceFilterArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Scope filter that further restricts which spans within a matched trace contribute to metrics or sampling. Only spans matching `span_scopes` are included in aggregation.
        /// </summary>
        [Input("scopeFilter")]
        public Input<Inputs.TraceMetricsRuleTraceFilterScopeFilterArgs>? ScopeFilter { get; set; }

        [Input("spans")]
        private InputList<Inputs.TraceMetricsRuleTraceFilterSpanArgs>? _spans;

        /// <summary>
        /// Span-level conditions. Each block defines a set of conditions that must all be satisfied by a single span in the trace for the trace to match.
        /// </summary>
        public InputList<Inputs.TraceMetricsRuleTraceFilterSpanArgs> Spans
        {
            get => _spans ?? (_spans = new InputList<Inputs.TraceMetricsRuleTraceFilterSpanArgs>());
            set => _spans = value;
        }

        /// <summary>
        /// Trace-level conditions evaluated against the whole trace (aggregated duration and error status).
        /// </summary>
        [Input("trace")]
        public Input<Inputs.TraceMetricsRuleTraceFilterTraceArgs>? Trace { get; set; }

        public TraceMetricsRuleTraceFilterArgs()
        {
        }
        public static new TraceMetricsRuleTraceFilterArgs Empty => new TraceMetricsRuleTraceFilterArgs();
    }
}
