// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Chronosphere.Inputs
{

    public sealed class TraceMetricsRuleGroupByKeyArgs : global::Pulumi.ResourceArgs
    {
        [Input("namedKey")]
        public Input<string>? NamedKey { get; set; }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public TraceMetricsRuleGroupByKeyArgs()
        {
        }
        public static new TraceMetricsRuleGroupByKeyArgs Empty => new TraceMetricsRuleGroupByKeyArgs();
    }
}
