// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Read-only data source that retrieves an existing bucket by name or slug. References buckets created outside of Terraform.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as chronosphere from "@pulumi-chronosphere/pulumi-chronosphere";
 *
 * const _default = chronosphere.BucketDataSource({
 *     slug: "default",
 * });
 * const byName = chronosphere.BucketDataSource({
 *     name: "Default",
 * });
 * ```
 */
export function bucketDataSource(args?: BucketDataSourceArgs, opts?: pulumi.InvokeOptions): Promise<BucketDataSourceResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("chronosphere:index/bucketDataSource:BucketDataSource", {
        "labels": args.labels,
        "name": args.name,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking BucketDataSource.
 */
export interface BucketDataSourceArgs {
    /**
     * Read-only: key/value labels attached to the bucket.
     */
    labels?: {[key: string]: string};
    /**
     * Name of the bucket to look up. Exactly one of `slug` or `name` must be set.
     */
    name?: string;
    /**
     * Slug of the bucket to look up. Exactly one of `slug` or `name` must be set.
     */
    slug?: string;
}

/**
 * A collection of values returned by BucketDataSource.
 */
export interface BucketDataSourceResult {
    /**
     * Read-only: free-form description of the bucket.
     */
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Read-only: key/value labels attached to the bucket.
     */
    readonly labels?: {[key: string]: string};
    /**
     * Name of the bucket to look up. Exactly one of `slug` or `name` must be set.
     */
    readonly name?: string;
    /**
     * Slug of the bucket to look up. Exactly one of `slug` or `name` must be set.
     */
    readonly slug?: string;
}
/**
 * Read-only data source that retrieves an existing bucket by name or slug. References buckets created outside of Terraform.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as chronosphere from "@pulumi-chronosphere/pulumi-chronosphere";
 *
 * const _default = chronosphere.BucketDataSource({
 *     slug: "default",
 * });
 * const byName = chronosphere.BucketDataSource({
 *     name: "Default",
 * });
 * ```
 */
export function bucketDataSourceOutput(args?: BucketDataSourceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<BucketDataSourceResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("chronosphere:index/bucketDataSource:BucketDataSource", {
        "labels": args.labels,
        "name": args.name,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking BucketDataSource.
 */
export interface BucketDataSourceOutputArgs {
    /**
     * Read-only: key/value labels attached to the bucket.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Name of the bucket to look up. Exactly one of `slug` or `name` must be set.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Slug of the bucket to look up. Exactly one of `slug` or `name` must be set.
     */
    slug?: pulumi.Input<string | undefined>;
}
