// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Chronosphere dashboard composed of panels, layouts, and variables defined by `dashboardJson`. For Grafana-compatible dashboards, use `chronosphere.ClassicDashboard` instead.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as chronosphere from "@pulumi-chronosphere/pulumi-chronosphere";
 *
 * const collection = new chronosphere.Collection("collection", {name: "Platform"});
 * const platform = new chronosphere.Dashboard("platform", {
 *     name: "Platform Overview",
 *     slug: "platform-overview",
 *     collectionId: collection.id,
 *     labels: {
 *         team: "platform",
 *     },
 *     dashboardJson: JSON.stringify({
 *         kind: "Dashboard",
 *         spec: {
 *             events: [],
 *             panels: {},
 *             layouts: [],
 *             variables: [],
 *             duration: "30m",
 *         },
 *         spec_version: "1",
 *     }),
 * });
 * ```
 */
export class Dashboard extends pulumi.CustomResource {
    /**
     * Get an existing Dashboard resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DashboardState, opts?: pulumi.CustomResourceOptions): Dashboard {
        return new Dashboard(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'chronosphere:index/dashboard:Dashboard';

    /**
     * Returns true if the given object is an instance of Dashboard.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Dashboard {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Dashboard.__pulumiType;
    }

    /**
     * ID of the collection that owns this dashboard.
     */
    public readonly collectionId!: pulumi.Output<string | undefined>;
    /**
     * JSON payload describing the dashboard's panels, layouts, variables, and other content. Wrap with `jsonencode({...})` in HCL. The provider sanitizes the JSON before diffing, so cosmetic differences (key ordering, whitespace) do not cause spurious plans.
     */
    public readonly dashboardJson!: pulumi.Output<string>;
    /**
     * Key/value labels attached to the dashboard for organization and filtering.
     */
    public readonly labels!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Display name of the dashboard. Can be changed after creation.
     */
    public readonly name!: pulumi.Output<string | undefined>;
    /**
     * Stable identifier for the dashboard. Generated from `name` if omitted. Immutable after creation.
     */
    public readonly slug!: pulumi.Output<string>;

    /**
     * Create a Dashboard resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DashboardArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DashboardArgs | DashboardState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DashboardState | undefined;
            resourceInputs["collectionId"] = state ? state.collectionId : undefined;
            resourceInputs["dashboardJson"] = state ? state.dashboardJson : undefined;
            resourceInputs["labels"] = state ? state.labels : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["slug"] = state ? state.slug : undefined;
        } else {
            const args = argsOrState as DashboardArgs | undefined;
            if ((!args || args.dashboardJson === undefined) && !opts.urn) {
                throw new Error("Missing required property 'dashboardJson'");
            }
            resourceInputs["collectionId"] = args ? args.collectionId : undefined;
            resourceInputs["dashboardJson"] = args ? args.dashboardJson : undefined;
            resourceInputs["labels"] = args ? args.labels : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["slug"] = args ? args.slug : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Dashboard.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Dashboard resources.
 */
export interface DashboardState {
    /**
     * ID of the collection that owns this dashboard.
     */
    collectionId?: pulumi.Input<string>;
    /**
     * JSON payload describing the dashboard's panels, layouts, variables, and other content. Wrap with `jsonencode({...})` in HCL. The provider sanitizes the JSON before diffing, so cosmetic differences (key ordering, whitespace) do not cause spurious plans.
     */
    dashboardJson?: pulumi.Input<string>;
    /**
     * Key/value labels attached to the dashboard for organization and filtering.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Display name of the dashboard. Can be changed after creation.
     */
    name?: pulumi.Input<string>;
    /**
     * Stable identifier for the dashboard. Generated from `name` if omitted. Immutable after creation.
     */
    slug?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Dashboard resource.
 */
export interface DashboardArgs {
    /**
     * ID of the collection that owns this dashboard.
     */
    collectionId?: pulumi.Input<string>;
    /**
     * JSON payload describing the dashboard's panels, layouts, variables, and other content. Wrap with `jsonencode({...})` in HCL. The provider sanitizes the JSON before diffing, so cosmetic differences (key ordering, whitespace) do not cause spurious plans.
     */
    dashboardJson: pulumi.Input<string>;
    /**
     * Key/value labels attached to the dashboard for organization and filtering.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Display name of the dashboard. Can be changed after creation.
     */
    name?: pulumi.Input<string>;
    /**
     * Stable identifier for the dashboard. Generated from `name` if omitted. Immutable after creation.
     */
    slug?: pulumi.Input<string>;
}
