// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Workspace-scoped OpsGenie credentials that downstream notifiers and LogScale actions can reference. Centralizes the OpsGenie API key so it isn't duplicated across individual notifiers; modern equivalent of the per-notifier credentials.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as chronosphere from "@pulumi-chronosphere/pulumi-chronosphere";
 *
 * const opsgenie = new chronosphere.OpsgenieExternalConnection("opsgenie", {
 *     apiKey: "XXXXX",
 *     apiUrl: "https://api.opsgenie.com/",
 *     name: "OpsGenie",
 * });
 * ```
 */
export class OpsgenieExternalConnection extends pulumi.CustomResource {
    /**
     * Get an existing OpsgenieExternalConnection resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OpsgenieExternalConnectionState, opts?: pulumi.CustomResourceOptions): OpsgenieExternalConnection {
        return new OpsgenieExternalConnection(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'chronosphere:index/opsgenieExternalConnection:OpsgenieExternalConnection';

    /**
     * Returns true if the given object is an instance of OpsgenieExternalConnection.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OpsgenieExternalConnection {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OpsgenieExternalConnection.__pulumiType;
    }

    /**
     * OpsGenie integration API key used to authenticate alert delivery. Treat as a secret.
     */
    declare public readonly apiKey: pulumi.Output<string | undefined>;
    /**
     * Base URL of the OpsGenie API. Override to target the EU region or a custom endpoint.
     */
    declare public readonly apiUrl: pulumi.Output<string | undefined>;
    /**
     * Password for HTTP basic auth when calling OpsGenie. Treat as a secret.
     */
    declare public readonly basicAuthPassword: pulumi.Output<string | undefined>;
    /**
     * Username for HTTP basic auth when calling OpsGenie. Mutually exclusive with `bearerToken`.
     */
    declare public readonly basicAuthUsername: pulumi.Output<string | undefined>;
    /**
     * Bearer token sent in the `Authorization` header when calling OpsGenie. Mutually exclusive with basic auth. Treat as a secret.
     */
    declare public readonly bearerToken: pulumi.Output<string | undefined>;
    /**
     * Display name of the external connection.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Stable identifier for the connection. Generated from `name` if omitted. Immutable after creation.
     */
    declare public readonly slug: pulumi.Output<string>;
    /**
     * If true, skip TLS certificate verification when calling OpsGenie. Disable only in trusted environments.
     */
    declare public readonly tlsInsecureSkipVerify: pulumi.Output<boolean | undefined>;

    /**
     * Create a OpsgenieExternalConnection resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OpsgenieExternalConnectionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OpsgenieExternalConnectionArgs | OpsgenieExternalConnectionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OpsgenieExternalConnectionState | undefined;
            resourceInputs["apiKey"] = state?.apiKey;
            resourceInputs["apiUrl"] = state?.apiUrl;
            resourceInputs["basicAuthPassword"] = state?.basicAuthPassword;
            resourceInputs["basicAuthUsername"] = state?.basicAuthUsername;
            resourceInputs["bearerToken"] = state?.bearerToken;
            resourceInputs["name"] = state?.name;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["tlsInsecureSkipVerify"] = state?.tlsInsecureSkipVerify;
        } else {
            const args = argsOrState as OpsgenieExternalConnectionArgs | undefined;
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["apiKey"] = args?.apiKey ? pulumi.secret(args.apiKey) : undefined;
            resourceInputs["apiUrl"] = args?.apiUrl;
            resourceInputs["basicAuthPassword"] = args?.basicAuthPassword ? pulumi.secret(args.basicAuthPassword) : undefined;
            resourceInputs["basicAuthUsername"] = args?.basicAuthUsername;
            resourceInputs["bearerToken"] = args?.bearerToken;
            resourceInputs["name"] = args?.name;
            resourceInputs["slug"] = args?.slug;
            resourceInputs["tlsInsecureSkipVerify"] = args?.tlsInsecureSkipVerify;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey", "basicAuthPassword"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(OpsgenieExternalConnection.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering OpsgenieExternalConnection resources.
 */
export interface OpsgenieExternalConnectionState {
    /**
     * OpsGenie integration API key used to authenticate alert delivery. Treat as a secret.
     */
    apiKey?: pulumi.Input<string | undefined>;
    /**
     * Base URL of the OpsGenie API. Override to target the EU region or a custom endpoint.
     */
    apiUrl?: pulumi.Input<string | undefined>;
    /**
     * Password for HTTP basic auth when calling OpsGenie. Treat as a secret.
     */
    basicAuthPassword?: pulumi.Input<string | undefined>;
    /**
     * Username for HTTP basic auth when calling OpsGenie. Mutually exclusive with `bearerToken`.
     */
    basicAuthUsername?: pulumi.Input<string | undefined>;
    /**
     * Bearer token sent in the `Authorization` header when calling OpsGenie. Mutually exclusive with basic auth. Treat as a secret.
     */
    bearerToken?: pulumi.Input<string | undefined>;
    /**
     * Display name of the external connection.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Stable identifier for the connection. Generated from `name` if omitted. Immutable after creation.
     */
    slug?: pulumi.Input<string | undefined>;
    /**
     * If true, skip TLS certificate verification when calling OpsGenie. Disable only in trusted environments.
     */
    tlsInsecureSkipVerify?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a OpsgenieExternalConnection resource.
 */
export interface OpsgenieExternalConnectionArgs {
    /**
     * OpsGenie integration API key used to authenticate alert delivery. Treat as a secret.
     */
    apiKey?: pulumi.Input<string | undefined>;
    /**
     * Base URL of the OpsGenie API. Override to target the EU region or a custom endpoint.
     */
    apiUrl?: pulumi.Input<string | undefined>;
    /**
     * Password for HTTP basic auth when calling OpsGenie. Treat as a secret.
     */
    basicAuthPassword?: pulumi.Input<string | undefined>;
    /**
     * Username for HTTP basic auth when calling OpsGenie. Mutually exclusive with `bearerToken`.
     */
    basicAuthUsername?: pulumi.Input<string | undefined>;
    /**
     * Bearer token sent in the `Authorization` header when calling OpsGenie. Mutually exclusive with basic auth. Treat as a secret.
     */
    bearerToken?: pulumi.Input<string | undefined>;
    /**
     * Display name of the external connection.
     */
    name: pulumi.Input<string>;
    /**
     * Stable identifier for the connection. Generated from `name` if omitted. Immutable after creation.
     */
    slug?: pulumi.Input<string | undefined>;
    /**
     * If true, skip TLS certificate verification when calling OpsGenie. Disable only in trusted environments.
     */
    tlsInsecureSkipVerify?: pulumi.Input<boolean | undefined>;
}
