// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * A service-level objective that tracks the ratio of good to total events produced by an SLI over a configured time window, with optional multi-window burn-rate alerting.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as chronosphere from "@pulumi-chronosphere/pulumi-chronosphere";
 *
 * const payments = new chronosphere.Team("payments", {name: "Payments"});
 * const blackhole = new chronosphere.BlackholeAlertNotifier("blackhole", {name: "Blackhole"});
 * const np = new chronosphere.NotificationPolicy("np", {
 *     name: "SLO policy",
 *     teamId: payments.id,
 *     routes: [{
 *         severity: "warn",
 *         notifiers: [blackhole.id],
 *     }],
 * });
 * const collection = new chronosphere.Collection("collection", {
 *     name: "Payments",
 *     teamId: payments.id,
 * });
 * const requestSuccess = new chronosphere.SLO("requestSuccess", {
 *     name: "payments request success",
 *     collectionId: collection.id,
 *     notificationPolicyId: np.id,
 *     definition: {
 *         objective: 99.95,
 *         timeWindow: {
 *             duration: "28d",
 *         },
 *         enableBurnRateAlerting: true,
 *     },
 *     sli: {
 *         customIndicator: {
 *             badQueryTemplate: "sum(rate(http_request_duration_seconds_count{error=\"true\"}[{{ .Window }}]))",
 *             totalQueryTemplate: "sum(rate(http_request_duration_seconds_count[{{ .Window }}]))",
 *         },
 *     },
 * });
 * ```
 */
export class SLO extends pulumi.CustomResource {
    /**
     * Get an existing SLO resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SLOState, opts?: pulumi.CustomResourceOptions): SLO {
        return new SLO(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'chronosphere:index/sLO:SLO';

    /**
     * Returns true if the given object is an instance of SLO.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SLO {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SLO.__pulumiType;
    }

    /**
     * Free-form key/value pairs included in notifications generated by this SLO. Templated against signal labels.
     */
    declare public readonly annotations: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * ID of the collection that owns this SLO.
     */
    declare public readonly collectionId: pulumi.Output<string>;
    /**
     * SLO definition specifying the objective, time window, and burn-rate alerting configuration.
     */
    declare public readonly definition: pulumi.Output<outputs.SLODefinition>;
    /**
     * Free-form description of the SLO.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Key/value labels attached to the SLO. Visible in notifications and usable for routing overrides in notification policies.
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Display name of the SLO. Can be changed after creation.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * ID of the notification policy used to route burn-rate alerts from this SLO. If omitted, the policy of the parent collection applies. Required if burn-rate alerting is enabled and the collection has no default policy.
     */
    declare public readonly notificationPolicyId: pulumi.Output<string | undefined>;
    /**
     * Controls how individual time series are grouped into signals for alerting purposes.
     */
    declare public readonly signalGrouping: pulumi.Output<outputs.SLOSignalGrouping | undefined>;
    /**
     * Service-level indicator (SLI) definition that produces the good/bad event ratio measured by this SLO.
     */
    declare public readonly sli: pulumi.Output<outputs.SLOSli>;
    /**
     * Stable identifier for the SLO. Generated from `name` if omitted. Immutable after creation.
     */
    declare public readonly slug: pulumi.Output<string>;

    /**
     * Create a SLO resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SLOArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SLOArgs | SLOState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SLOState | undefined;
            resourceInputs["annotations"] = state?.annotations;
            resourceInputs["collectionId"] = state?.collectionId;
            resourceInputs["definition"] = state?.definition;
            resourceInputs["description"] = state?.description;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["name"] = state?.name;
            resourceInputs["notificationPolicyId"] = state?.notificationPolicyId;
            resourceInputs["signalGrouping"] = state?.signalGrouping;
            resourceInputs["sli"] = state?.sli;
            resourceInputs["slug"] = state?.slug;
        } else {
            const args = argsOrState as SLOArgs | undefined;
            if (args?.collectionId === undefined && !opts.urn) {
                throw new Error("Missing required property 'collectionId'");
            }
            if (args?.definition === undefined && !opts.urn) {
                throw new Error("Missing required property 'definition'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.sli === undefined && !opts.urn) {
                throw new Error("Missing required property 'sli'");
            }
            resourceInputs["annotations"] = args?.annotations;
            resourceInputs["collectionId"] = args?.collectionId;
            resourceInputs["definition"] = args?.definition;
            resourceInputs["description"] = args?.description;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["name"] = args?.name;
            resourceInputs["notificationPolicyId"] = args?.notificationPolicyId;
            resourceInputs["signalGrouping"] = args?.signalGrouping;
            resourceInputs["sli"] = args?.sli;
            resourceInputs["slug"] = args?.slug;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SLO.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SLO resources.
 */
export interface SLOState {
    /**
     * Free-form key/value pairs included in notifications generated by this SLO. Templated against signal labels.
     */
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * ID of the collection that owns this SLO.
     */
    collectionId?: pulumi.Input<string | undefined>;
    /**
     * SLO definition specifying the objective, time window, and burn-rate alerting configuration.
     */
    definition?: pulumi.Input<inputs.SLODefinition | undefined>;
    /**
     * Free-form description of the SLO.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Key/value labels attached to the SLO. Visible in notifications and usable for routing overrides in notification policies.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Display name of the SLO. Can be changed after creation.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * ID of the notification policy used to route burn-rate alerts from this SLO. If omitted, the policy of the parent collection applies. Required if burn-rate alerting is enabled and the collection has no default policy.
     */
    notificationPolicyId?: pulumi.Input<string | undefined>;
    /**
     * Controls how individual time series are grouped into signals for alerting purposes.
     */
    signalGrouping?: pulumi.Input<inputs.SLOSignalGrouping | undefined>;
    /**
     * Service-level indicator (SLI) definition that produces the good/bad event ratio measured by this SLO.
     */
    sli?: pulumi.Input<inputs.SLOSli | undefined>;
    /**
     * Stable identifier for the SLO. Generated from `name` if omitted. Immutable after creation.
     */
    slug?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SLO resource.
 */
export interface SLOArgs {
    /**
     * Free-form key/value pairs included in notifications generated by this SLO. Templated against signal labels.
     */
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * ID of the collection that owns this SLO.
     */
    collectionId: pulumi.Input<string>;
    /**
     * SLO definition specifying the objective, time window, and burn-rate alerting configuration.
     */
    definition: pulumi.Input<inputs.SLODefinition>;
    /**
     * Free-form description of the SLO.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Key/value labels attached to the SLO. Visible in notifications and usable for routing overrides in notification policies.
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Display name of the SLO. Can be changed after creation.
     */
    name: pulumi.Input<string>;
    /**
     * ID of the notification policy used to route burn-rate alerts from this SLO. If omitted, the policy of the parent collection applies. Required if burn-rate alerting is enabled and the collection has no default policy.
     */
    notificationPolicyId?: pulumi.Input<string | undefined>;
    /**
     * Controls how individual time series are grouped into signals for alerting purposes.
     */
    signalGrouping?: pulumi.Input<inputs.SLOSignalGrouping | undefined>;
    /**
     * Service-level indicator (SLI) definition that produces the good/bad event ratio measured by this SLO.
     */
    sli: pulumi.Input<inputs.SLOSli>;
    /**
     * Stable identifier for the SLO. Generated from `name` if omitted. Immutable after creation.
     */
    slug?: pulumi.Input<string | undefined>;
}
