// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Chronosphere.Pulumi.Chronosphere.Outputs
{

    [OutputType]
    public sealed class GcpMetricsIntegrationMetricGroup
    {
        public readonly ImmutableArray<string> Prefixes;
        public readonly string ProjectId;

        [OutputConstructor]
        private GcpMetricsIntegrationMetricGroup(
            ImmutableArray<string> prefixes,

            string projectId)
        {
            Prefixes = prefixes;
            ProjectId = projectId;
        }
    }
}
